//--- OBJECT WRITE BEGIN ---
new ScriptObject(action_RoamingGamerAtoms_Misc_TakeAction) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "Rendering";
      description = "take the specified action.";
      details_atomName = "TakeAction";
      details_category = "Roaming Gamer Atoms";
      details_eventAction = "action";
      details_subCategory = "Misc";
      friendlyName = "TakeAction";
      segmentbehaviorFields = "2";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Action\", \"Action to take when a collision has been held for the specified duration.\", \"enum\",\"quit\", \"quit\" TAB \"load named level\" TAB \"load numbered level\" TAB\"load next numbered level\" TAB \"load last numbered level\" TAB \"reload current level\" TAB \"execute script\" TAB \"broadcast behavior method\"); ";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"userData\", \"Data specific to the action you wish to take. (Not required for all actions)\", \"default\", \"\");   ";
      segmentexecuteAction = "42";
      segmentexecuteAction_0 = "   switch$( %this.Action )";
      segmentexecuteAction_1 = "   {";
      segmentexecuteAction_10 = "   case \"load next numbered level\": // Load next numbered level";
      segmentexecuteAction_11 = "      sceneWindow2D.loadNextNumberedLevel();";
      segmentexecuteAction_12 = "   ";
      segmentexecuteAction_13 = "   case \"load last numbered level\": // Load last numbered level";
      segmentexecuteAction_14 = "      sceneWindow2D.loadLastNumberedLevel( );";
      segmentexecuteAction_15 = " ";
      segmentexecuteAction_16 = "   case \"reload current level\": // Reload the current level";
      segmentexecuteAction_17 = "      sceneWindow2D.reloadCurrentLevel( );";
      segmentexecuteAction_18 = "   ";
      segmentexecuteAction_19 = "   case \"execute script\": // Call the function specified in userData";
      segmentexecuteAction_2 = "   case \"quit\": // quit()";
      segmentexecuteAction_20 = "      %evalScript = %this.userData;";
      segmentexecuteAction_21 = "      //error( %evalScript );";
      segmentexecuteAction_22 = "      eval( %evalScript );   ";
      segmentexecuteAction_23 = "   ";
      segmentexecuteAction_24 = "   case \"execute owner method\": // Call the function specified in userData as a method.";
      segmentexecuteAction_25 = "      %owner = %this.owner;";
      segmentexecuteAction_26 = "      %evalScript = %owner.getID() @ \".\" @ %this.userData;";
      segmentexecuteAction_27 = "      //error( %evalScript );";
      segmentexecuteAction_28 = "      eval( %evalScript );   ";
      segmentexecuteAction_29 = "   ";
      segmentexecuteAction_3 = "      quit();";
      segmentexecuteAction_30 = "   case \"broadcast behavior method\":  // Call \'broadcastMethod\' with arguments";
      segmentexecuteAction_31 = "      %this.broadcastMethod( %this.userData );";
      segmentexecuteAction_32 = "   }";
      segmentexecuteAction_33 = "   ";
      segmentexecuteAction_34 = "   if(%this.repeat)";
      segmentexecuteAction_35 = "   {";
      segmentexecuteAction_36 = "      %this.ActionComplete     = false;";
      segmentexecuteAction_37 = "      %this.initialContactTime = 0;";
      segmentexecuteAction_38 = "      %this.lastContactTime    = 0;";
      segmentexecuteAction_39 = "      %this.sustatinedDuration = 0;";
      segmentexecuteAction_4 = "         ";
      segmentexecuteAction_40 = "      %this.lastContactObject  = 0;";
      segmentexecuteAction_41 = "   }";
      segmentexecuteAction_5 = "   case \"load named level\": // Load a named level file";
      segmentexecuteAction_6 = "      sceneWindow2D.loadNamedLevel(%this.userData);   ";
      segmentexecuteAction_7 = "   case \"load named level\": // Load a named level file";
      segmentexecuteAction_8 = "      sceneWindow2D.loadNumberedLevel(%this.userData);   ";
      segmentexecuteAction_9 = "      ";
      segments = "behaviorFields\texecuteAction";
};
//--- OBJECT WRITE END ---
