//--- OBJECT WRITE BEGIN ---
new ScriptObject(event_RoamingGamerAtoms_Collision_onSustainedContact) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "Collision Event ->";
      description = "When this object is in sustained contact (collision) with another object for a specified duration";
      details_atomName = "onSustainedContact";
      details_category = "Roaming Gamer Atoms";
      details_eventAction = "event";
      details_subCategory = "Collision";
      friendlyName = "onSustainedContact() ->";
      segmentbehaviorFields = "3";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField(\"Duration\", \"Specifies amount of time (in milliseconds) the collision needs to be maintained in order for the action to take place. (Minimum value is 100.)\", integer, 1000);";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Delay\", \"Once the collision duration is reached, wait this long before executing the action.\", integer, 0);";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"repeat\", \"If true, repeated sustained collisions will repeat the specified action.\", bool, false);";
      segmentkeepAll = "8";
      segmentkeepAll_0 = "function onSustainedContact::enableRepeat( %this )";
      segmentkeepAll_1 = "{";
      segmentkeepAll_2 = "   %this.ActionComplete     = false;";
      segmentkeepAll_3 = "   %this.initialContactTime = 0;";
      segmentkeepAll_4 = "   %this.lastContactTime    = 0;";
      segmentkeepAll_5 = "   %this.sustatinedDuration = 0;";
      segmentkeepAll_6 = "   %this.lastContactObject  = 0;";
      segmentkeepAll_7 = "}";
      segmentonAddToScene = "11";
      segmentonAddToScene_0 = "   if( %this.Duration < 100 ) %this.Duration = 100;";
      segmentonAddToScene_1 = "   ";
      segmentonAddToScene_10 = "                           // the new collision to be the beginning of a new duration and start counting again.                    ";
      segmentonAddToScene_2 = "   %this.ActionComplete     = false;";
      segmentonAddToScene_3 = "   %this.initialContactTime = 0;";
      segmentonAddToScene_4 = "   %this.lastContactTime    = 0;";
      segmentonAddToScene_5 = "   %this.sustatinedDuration = 0;";
      segmentonAddToScene_6 = "   %this.lastContactObject  = 0;";
      segmentonAddToScene_7 = "   ";
      segmentonAddToScene_8 = "   %this.toleranceMS = 99; // Maximum time betweeen collision updates before we consider a collision to be \'NEW\' again.";
      segmentonAddToScene_9 = "                           // i.e. if we have a collision and the next update comes more than 99 ms later, we consider ";
      segmentonCollision = "38";
      segmentonCollision_0 = "   if (%this.ActionComplete) return;";
      segmentonCollision_1 = "   ";
      segmentonCollision_10 = "      %this.sustatinedDuration = 0;";
      segmentonCollision_11 = "      %this.lastContactObject  = %dstObject;      ";
      segmentonCollision_12 = "   }";
      segmentonCollision_13 = "   // Check if we have exceeded our tween-collision tolerance";
      segmentonCollision_14 = "   // If so, treat this as a new collision and start counting again.";
      segmentonCollision_15 = "   else if ( (%currentTime - %this.lastContactTime) > %this.toleranceMS )";
      segmentonCollision_16 = "   {";
      segmentonCollision_17 = "      %this.ActionComplete     = false;";
      segmentonCollision_18 = "      %this.lastContactTime    = %currentTime;";
      segmentonCollision_19 = "      %this.initialContactTime = %currentTime;";
      segmentonCollision_2 = "   %currentTime = getSimTime();";
      segmentonCollision_20 = "      %this.sustatinedDuration = 0;";
      segmentonCollision_21 = "      %this.lastContactObject  = %dstObject;    ";
      segmentonCollision_22 = "   }";
      segmentonCollision_23 = "   // check to see if our duration has been reached and if so, execute the selected action";
      segmentonCollision_24 = "   else if ( (%currentTime - %this.initialContactTime) >= %this.Duration )";
      segmentonCollision_25 = "   {";
      segmentonCollision_26 = "      %this.ActionComplete     = true;   ";
      segmentonCollision_27 = "      schedule(%this.Delay, executeAction);";
      segmentonCollision_28 = "      if(%this.repeat)";
      segmentonCollision_29 = "      {   ";
      segmentonCollision_3 = "   ";
      segmentonCollision_30 = "         schedule(%this.Delay, enableRepeat); ";
      segmentonCollision_31 = "      }";
      segmentonCollision_32 = "    ";
      segmentonCollision_33 = "   }";
      segmentonCollision_34 = "   else";
      segmentonCollision_35 = "   {";
      segmentonCollision_36 = "      %this.lastContactTime    = %currentTime;      ";
      segmentonCollision_37 = "   }  ";
      segmentonCollision_4 = "   // Check for a new collision";
      segmentonCollision_5 = "   if(%dstObject != %this.lastContactObject)";
      segmentonCollision_6 = "   {";
      segmentonCollision_7 = "      %this.ActionComplete     = false;";
      segmentonCollision_8 = "      %this.lastContactTime    = %currentTime;";
      segmentonCollision_9 = "      %this.initialContactTime = %currentTime;";
      segments = "behaviorFields\tonAddToScene\tonCollision\tkeepAll";
};
//--- OBJECT WRITE END ---
