//--- OBJECT WRITE BEGIN ---
new ScriptObject(event_RoamingGamerAtoms_Trigger_onTrigger) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "Trigger Event ->";
      description = "When an object enters/stays/leaves this trigger";
      details_atomName = "onTrigger";
      details_category = "Roaming Gamer Atoms";
      details_eventAction = "event";
      details_subCategory = "Trigger";
      friendlyName = "onTrigger() ->";
      segmentbehaviorFields = "9";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"onEnter_Count\",  \"Maximum times onEnter() may be triggered [<0 = infinite; 0 - never] for this behavior.\", int, -1 );";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"onStay_Count\",  \"Maximum times onStay() may be triggered [<0 = infinite; 0 - never] for this behavior.\", int, 0 );";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"onLeave_Count\",  \"Maximum times onStay() may be triggered [<0 = infinite; 0 - never] for this behavior.\", int, 0 );";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"onEnter_Period\",  \"Times per second onEnter() can trigger [0 = no min delay].\", int, 0 );";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"onStay_Period\",  \"Times per second onStay() can trigger [0 = no min delay].\", int, 0 );";
      segmentbehaviorFields_5 = "   %behavior.addBehaviorField( \"onLeave_Period\",  \"Times per second onLeave() can trigger [0 = no min delay].\", int, 0 );";
      segmentbehaviorFields_6 = "   %behavior.addBehaviorField( \"onEnter_Delay\",  \"Delay (in MS) before onEnter() action.\", int, 0 );";
      segmentbehaviorFields_7 = "   %behavior.addBehaviorField( \"onStay_Delay\",  \"Delay (in MS) before onStay() action.\", int, 0 );";
      segmentbehaviorFields_8 = "   %behavior.addBehaviorField( \"onLeave_Delay\",  \"Delay (in MS) before onLeave() action.\", int, 0 );";
      segmentonAddToScene = "10";
      segmentonAddToScene_0 = "   // Init trigger counters";
      segmentonAddToScene_1 = "   %this.onEnter_Counter = 0;";
      segmentonAddToScene_2 = "   %this.onStay_Counter = 0;";
      segmentonAddToScene_3 = "   %this.onLeave_Counter = 0;";
      segmentonAddToScene_4 = "   ";
      segmentonAddToScene_5 = "   // Init Period counters";
      segmentonAddToScene_6 = "   %curTime = getSimTime();";
      segmentonAddToScene_7 = "   %this.onEnter_Period_Last = %curTime;";
      segmentonAddToScene_8 = "   %this.onStay_Period_Last = %curTime;";
      segmentonAddToScene_9 = "   %this.onLeave_Period_Last = %curTime;";
      segmentonEnter = "17";
      segmentonEnter_0 = "   if(%this.onEnter_Count == 0) return; // Effectively disables this callback";
      segmentonEnter_1 = "   if( (%this.onEnter_Count > 0) &&";
      segmentonEnter_10 = "   {  ";
      segmentonEnter_11 = "      %this.schedule( %this.onEnter_Delay, executeAction );";
      segmentonEnter_12 = "   }";
      segmentonEnter_13 = "   else";
      segmentonEnter_14 = "   {";
      segmentonEnter_15 = "      %this.executeAction();";
      segmentonEnter_16 = "   }";
      segmentonEnter_2 = "       (%this.onEnter_Counter >= %this.onEnter_Count) ) return;";
      segmentonEnter_3 = "   %curTime = getSimTime();";
      segmentonEnter_4 = "   if( (%this.onEnter_Period > 0) &&";
      segmentonEnter_5 = "       (%curTime - %this.onEnter_Period_Last) < %this.onEnter_Period ) return;";
      segmentonEnter_6 = "              ";
      segmentonEnter_7 = "   %this.onEnter_Period_Last = %curTime;";
      segmentonEnter_8 = "   %this.onEnter_Counter++;";
      segmentonEnter_9 = "   if(%this.onEnter_Delay > 0) ";
      segmentonLeave = "17";
      segmentonLeave_0 = "   if(%this.onLeave_Count == 0) return; // Effectively disables this callback";
      segmentonLeave_1 = "   if( (%this.onLeave_Count > 0) &&";
      segmentonLeave_10 = "   {  ";
      segmentonLeave_11 = "      %this.schedule( %this.onLeave_Delay, executeAction );";
      segmentonLeave_12 = "   }";
      segmentonLeave_13 = "   else";
      segmentonLeave_14 = "   {";
      segmentonLeave_15 = "      %this.executeAction();";
      segmentonLeave_16 = "   }";
      segmentonLeave_2 = "       (%this.onLeave_Counter >= %this.onLeave_Count) ) return;";
      segmentonLeave_3 = "   %curTime = getSimTime();";
      segmentonLeave_4 = "   if( (%this.onLeave_Period > 0) &&";
      segmentonLeave_5 = "       (%curTime - %this.onLeave_Period_Last) < %this.onLeave_Period ) return;";
      segmentonLeave_6 = "              ";
      segmentonLeave_7 = "   %this.onLeave_Period_Last = %curTime;";
      segmentonLeave_8 = "   %this.onLeave_Counter++;";
      segmentonLeave_9 = "   if(%this.onLeave_Delay > 0) ";
      segmentonStay = "17";
      segmentonStay_0 = "   if(%this.onStay_Count == 0) return; // Effectively disables this callback";
      segmentonStay_1 = "   if( (%this.onStay_Count > 0) &&";
      segmentonStay_10 = "   {  ";
      segmentonStay_11 = "      %this.schedule( %this.onStay_Delay, executeAction );";
      segmentonStay_12 = "   }";
      segmentonStay_13 = "   else";
      segmentonStay_14 = "   {";
      segmentonStay_15 = "      %this.executeAction();";
      segmentonStay_16 = "   }";
      segmentonStay_2 = "       (%this.onStay_Counter >= %this.onStay_Count) ) return;";
      segmentonStay_3 = "   %curTime = getSimTime();";
      segmentonStay_4 = "   if( (%this.onStay_Period > 0) &&";
      segmentonStay_5 = "       (%curTime - %this.onStay_Period_Last) < %this.onStay_Period ) return;";
      segmentonStay_6 = "              ";
      segmentonStay_7 = "   %this.onStay_Period_Last = %curTime;";
      segmentonStay_8 = "   %this.onStay_Counter++;";
      segmentonStay_9 = "   if(%this.onStay_Delay > 0) ";
      segments = "behaviorFields\tonAddToScene\tonEnter\tonStay\tonLeave";
};
//--- OBJECT WRITE END ---
