//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_00RapidPrototyping_Configuration_UseQuickConfig) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "00 - Rapid Prototyping";
      description = "Assigns a QC type to this object and configures the object to use it.";
      details_atomName = "UseQuickConfig";
      details_category = "00 - Rapid Prototyping";
      details_eventAction = "full";
      details_subCategory = "Configuration";
      friendlyName = "Use Quick Config";
      segmentbehaviorFields = "6";
      segmentbehaviorFields_0 = "   %typeList = RGQC.getKnownTypes(); //addBehaviorField - trick so line is kept during parse";
      segmentbehaviorFields_1 = "   %firstType = getWord( %typeList , 0 ); //addBehaviorField - trick so line is kept during parse";
      segmentbehaviorFields_2 = "   %typelist = strreplace( %typelist, \" \", \"\\t\"); //addBehaviorField - trick so line is kept during parse";
      segmentbehaviorFields_3 = "   %typelist = strlwr(%typelist); //addBehaviorField - trick so line is kept during parse";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"MyType\", \"Type name for this object.\", \"enum\", %firstType, %typeList);";
      segmentbehaviorFields_5 = "   %behavior.addBehaviorField( \"KnownTypes\", \"Copy Known Types To Clipboard\", \"functionButton\", \"\", \"setClipboard( strreplace(RGQC.getKnownTypes(), \\\" \\\", \\\",\\\" ) );\");      ";
      segmentkeepAll = "20";
      segmentkeepAll_0 = "// This (hack) updates the owner object based on the current type selected, keeping the object\'s attributes up-to-date in the editor\\";
      segmentkeepAll_1 = "// It loops once a second and only updates when a change is detected";
      segmentkeepAll_10 = "   }";
      segmentkeepAll_11 = "   ";
      segmentkeepAll_12 = "   if(%this.lastType !$= %this.MyType )";
      segmentkeepAll_13 = "   {      ";
      segmentkeepAll_14 = "      RGQC.applyQC( %this.owner, %this.MyType  );";
      segmentkeepAll_15 = "      %this.lastType = %this.MyType;";
      segmentkeepAll_16 = "   }";
      segmentkeepAll_17 = "   ";
      segmentkeepAll_18 = "   %this.schedule(1000, liveUpdate);";
      segmentkeepAll_19 = "}";
      segmentkeepAll_2 = "function UseQuickConfig::liveUpdate(%this) ";
      segmentkeepAll_3 = "{";
      segmentkeepAll_4 = "   if(!$LevelEditorActive) return;";
      segmentkeepAll_5 = "   ";
      segmentkeepAll_6 = "   if(!isObject(RGQC)) ";
      segmentkeepAll_7 = "   {";
      segmentkeepAll_8 = "      error(\"UseQuickConfig::liveUpdate() - RGQC object not present... aborting.\");";
      segmentkeepAll_9 = "      return;";
      segmentonAddToScene = "9";
      segmentonAddToScene_0 = "   RGQC::Prolog();";
      segmentonAddToScene_1 = "   ";
      segmentonAddToScene_2 = "   if(%this.debugMode)  echo(\"Owner (\", %this.owner, \") name: \", %this.owner.getName());";
      segmentonAddToScene_3 = "   if(!isObject(RGQC)) ";
      segmentonAddToScene_4 = "   {";
      segmentonAddToScene_5 = "      error(\"RG_UseQuickConfig::onAddToScene() - RGQC object not present... aborting.\");";
      segmentonAddToScene_6 = "      return;";
      segmentonAddToScene_7 = "   }";
      segmentonAddToScene_8 = "   RGQC.applyQC( %this.owner, %this.MyType  );";
      segmentonBehaviorAdd = "2";
      segmentonBehaviorAdd_0 = "   RGQC::Prolog();";
      segmentonBehaviorAdd_1 = "   %this.liveUpdate();";
      segmentonCollision = "21";
      segmentonCollision_0 = "   %srcOwner = %this.owner;";
      segmentonCollision_1 = "   %dstOwner = %dstObj;   ";
      segmentonCollision_10 = "   if(%this.debugMode) echo(\"%dstType (collidee) == \", %dstType);";
      segmentonCollision_11 = "   ";
      segmentonCollision_12 = "   // Apply any collision damage";
      segmentonCollision_13 = "   %colDamage = RGQC.getDamage_onCollisionAmount( %srcType, %dstType );";
      segmentonCollision_14 = "   if(%this.debugMode) echo(\"%colDamage == \", %colDamage);";
      segmentonCollision_15 = "   if(%colDamage != 0) %dstOwner.applyDamage( %colDamage );";
      segmentonCollision_16 = "   ";
      segmentonCollision_17 = "   // Apply any collision drain";
      segmentonCollision_18 = "   %colDrain = RGQC.getDrain_onCollisionAmount( %srcType, %dstType );";
      segmentonCollision_19 = "   if(%this.debugMode) echo(\"%colDrain == \", %colDrain);";
      segmentonCollision_2 = "   if(%this.debugMode) echo(\"%srcOwner == \", %srcOwner);";
      segmentonCollision_20 = "   if(%colDrain != 0) %dstOwner.drainEnergy( %colDrain );";
      segmentonCollision_3 = "   if(%this.debugMode) echo(\"%dstOwner == \", %dstOwner);";
      segmentonCollision_4 = "   %srcBehavior = %this;";
      segmentonCollision_5 = "   %dstBehavior = %dstObj.getBehavior( \"UseQuickConfig\" );   ";
      segmentonCollision_6 = "   %srcType = %srcBehavior.myType;";
      segmentonCollision_7 = "   %dstType = %dstBehavior.myType;   ";
      segmentonCollision_8 = "   ";
      segmentonCollision_9 = "   if(%this.debugMode) echo(\"%srcType (collider) == \", %srcType);";
      segments = "behaviorFields\tonBehaviorAdd\tonAddToScene\tonCollision\tkeepAll";
};
//--- OBJECT WRITE END ---
