//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveThrustRightMouseDepressed) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Accelerate forward while mouse button is depressed.";
      details_atomName = "moveThrustRightMouseDepressed";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Right Mouse Thrust";
      segmentbehaviorFields = "1";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Thrust\", \"Thrusting power.\", float, 100 );       ";
      segmentkeepAll = "5";
      segmentkeepAll_0 = "function moveThrustRightMouseDepressed::doThrust(%this, %val)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_2 = "   error(\"doThrust => \", %val);";
      segmentkeepAll_3 = "   %this.owner.setConstantForcePolar( %this.owner.getRotation(), %val * %this.Thrust  , true ); ";
      segmentkeepAll_4 = "}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonRightMouseDown = "2";
      segmentonRightMouseDown_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDown_1 = "   %this.doThrust( 1 );";
      segmentonRightMouseUp = "2";
      segmentonRightMouseUp_0 = "   if (!%this.enable) return;";
      segmentonRightMouseUp_1 = "   %this.doThrust( 0 );";
      segments = "behaviorFields\tonAddToScene\tonRightMouseDown\tonRightMouseUp\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveThrustMouseDepressed) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Accelerate forward while mouse button is depressed.";
      details_atomName = "moveThrustMouseDepressed";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Mouse Thrust";
      segmentbehaviorFields = "1";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Thrust\", \"Thrusting power.\", float, 100 );       ";
      segmentkeepAll = "5";
      segmentkeepAll_0 = "function moveThrustMouseDepressed::doThrust(%this, %val)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_2 = "   error(\"doThrust => \", %val);";
      segmentkeepAll_3 = "   %this.owner.setConstantForcePolar( %this.owner.getRotation(), %val * %this.Thrust  , true ); ";
      segmentkeepAll_4 = "}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDown = "2";
      segmentonMouseDown_0 = "   if (!%this.enable) return;";
      segmentonMouseDown_1 = "   %this.doThrust( 1 );";
      segmentonMouseUp = "2";
      segmentonMouseUp_0 = "   if (!%this.enable) return;";
      segmentonMouseUp_1 = "   %this.doThrust( 0 );";
      segments = "behaviorFields\tonAddToScene\tonMouseDown\tonMouseUp\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveStopRightMouseClick) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Stop translations and/or rotations when right mouse buttons is clicked.";
      details_atomName = "moveStopRightMouseClick";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Right Mouse Stop";
      segmentbehaviorFields = "2";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Stop_Translations\",  \"Stop translations.\", bool, true );";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Stop_Rotations\",  \"Stop rotations.\", bool, true );}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonRightMouseDown = "21";
      segmentonRightMouseDown_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDown_1 = "   ";
      segmentonRightMouseDown_10 = "      %this.owner.setLinearVelocity(0,0);";
      segmentonRightMouseDown_11 = "      //%this.owner.setConstantForcePolar( 0, 0 );";
      segmentonRightMouseDown_12 = "      %this.owner.stopConstantForce(0,0);";
      segmentonRightMouseDown_13 = "      %this.setPositionTargetOff();";
      segmentonRightMouseDown_14 = "   }";
      segmentonRightMouseDown_15 = "   else if(%this.Stop_Rotations)";
      segmentonRightMouseDown_16 = "   {";
      segmentonRightMouseDown_17 = "      error(\"Stop Rotations\" );";
      segmentonRightMouseDown_18 = "      %this.setRotationTargetOff();";
      segmentonRightMouseDown_19 = "      %this.setAngularVelocity( 0.0 );";
      segmentonRightMouseDown_2 = "   if(%this.Stop_Translations && %this.Stop_Rotations)";
      segmentonRightMouseDown_20 = "   }";
      segmentonRightMouseDown_3 = "   {";
      segmentonRightMouseDown_4 = "      error(\"Stop Translations and Rotations\" );";
      segmentonRightMouseDown_5 = "      %this.owner.setAtRest();";
      segmentonRightMouseDown_6 = "   }   ";
      segmentonRightMouseDown_7 = "   else if(%this.Stop_Translations)";
      segmentonRightMouseDown_8 = "   {";
      segmentonRightMouseDown_9 = "      error(\"Stop Translations\" );";
      segments = "behaviorFields\tonAddToScene\tonRightMouseDown";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveStopMouseClick) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Stop translations and/or rotations when mouse buttons is clicked.";
      details_atomName = "moveStopMouseClick";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Mouse Stop";
      segmentbehaviorFields = "2";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Stop_Translations\",  \"Stop translations.\", bool, true );";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Stop_Rotations\",  \"Stop rotations.\", bool, true );}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDown = "21";
      segmentonMouseDown_0 = "   if (!%this.enable) return;";
      segmentonMouseDown_1 = "   ";
      segmentonMouseDown_10 = "      %this.owner.setLinearVelocity(0,0);";
      segmentonMouseDown_11 = "      //%this.owner.setConstantForcePolar( 0, 0 );";
      segmentonMouseDown_12 = "      %this.owner.stopConstantForce(0,0);";
      segmentonMouseDown_13 = "      %this.setPositionTargetOff();";
      segmentonMouseDown_14 = "   }";
      segmentonMouseDown_15 = "   else if(%this.Stop_Rotations)";
      segmentonMouseDown_16 = "   {";
      segmentonMouseDown_17 = "      error(\"Stop Rotations\" );";
      segmentonMouseDown_18 = "      %this.setRotationTargetOff();";
      segmentonMouseDown_19 = "      %this.setAngularVelocity( 0.0 );";
      segmentonMouseDown_2 = "   if(%this.Stop_Translations && %this.Stop_Rotations)";
      segmentonMouseDown_20 = "   }";
      segmentonMouseDown_3 = "   {";
      segmentonMouseDown_4 = "      error(\"Stop Translations and Rotations\" );";
      segmentonMouseDown_5 = "      %this.owner.setAtRest();";
      segmentonMouseDown_6 = "   }   ";
      segmentonMouseDown_7 = "   else if(%this.Stop_Translations)";
      segmentonMouseDown_8 = "   {";
      segmentonMouseDown_9 = "      error(\"Stop Translations\" );";
      segments = "behaviorFields\tonAddToScene\tonMouseDown";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveRotateRightMouseDrag) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Rotate when mouse is right dragged left or right.";
      details_atomName = "moveRotateRightMouseDrag";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Rotate Right Mouse Drag";
      segmentbehaviorFields = "1";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField(turnSpeed, \"Turn rate (in degrees per pixel moved)\", float, 1.0);";
      segmentkeepAll = "16";
      segmentkeepAll_0 = "function moveRotateRightMouseDrag::doRotate(%this, %worldPos)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_10 = "   %deltaX = %deltaX * %this.turnSpeed;";
      segmentkeepAll_11 = "   ";
      segmentkeepAll_12 = "   %currentAngle = %this.owner.getRotation();";
      segmentkeepAll_13 = "   ";
      segmentkeepAll_14 = "   %this.owner.setRotation(%currentAngle + %deltaX);";
      segmentkeepAll_15 = "}";
      segmentkeepAll_2 = "   %newPos = %worldPos;   ";
      segmentkeepAll_3 = "   %oldPos = %this.lastPos;";
      segmentkeepAll_4 = "   %this.lastPos = %newPos;";
      segmentkeepAll_5 = "   ";
      segmentkeepAll_6 = "   %vector = t2dVectorSub( %newPos, %oldPos );";
      segmentkeepAll_7 = "   ";
      segmentkeepAll_8 = "   %deltaX = getWord( %vector , 0 );";
      segmentkeepAll_9 = "   ";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonRightMouseDown = "2";
      segmentonRightMouseDown_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDown_1 = "   %this.lastPos = %worldPos;";
      segmentonRightMouseDragged = "2";
      segmentonRightMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDragged_1 = "   %this.doRotate( %worldPos );";
      segments = "behaviorFields\tonAddToScene\tonRightMouseDown\tonRightMouseDragged\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveRotateMouseDrag) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Rotate when mouse is dragged left or right.";
      details_atomName = "moveRotateMouseDrag";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Rotate Mouse Drag";
      segmentbehaviorFields = "1";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField(turnSpeed, \"Turn rate (in degrees per pixel moved)\", float, 1.0);";
      segmentkeepAll = "16";
      segmentkeepAll_0 = "function moveRotateMouseDrag::doRotate(%this, %worldPos)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_10 = "   %deltaX = %deltaX * %this.turnSpeed;";
      segmentkeepAll_11 = "   ";
      segmentkeepAll_12 = "   %currentAngle = %this.owner.getRotation();";
      segmentkeepAll_13 = "   ";
      segmentkeepAll_14 = "   %this.owner.setRotation(%currentAngle + %deltaX);";
      segmentkeepAll_15 = "}";
      segmentkeepAll_2 = "   %newPos = %worldPos;   ";
      segmentkeepAll_3 = "   %oldPos = %this.lastPos;";
      segmentkeepAll_4 = "   %this.lastPos = %newPos;";
      segmentkeepAll_5 = "   ";
      segmentkeepAll_6 = "   %vector = t2dVectorSub( %newPos, %oldPos );";
      segmentkeepAll_7 = "   ";
      segmentkeepAll_8 = "   %deltaX = getWord( %vector , 0 );";
      segmentkeepAll_9 = "   ";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDown = "2";
      segmentonMouseDown_0 = "   if (!%this.enable) return;";
      segmentonMouseDown_1 = "   %this.lastPos = %worldPos;";
      segmentonMouseDragged = "2";
      segmentonMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonMouseDragged_1 = "   %this.doRotate( %worldPos );";
      segments = "behaviorFields\tonAddToScene\tonMouseDown\tonMouseDragged\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveRotateMouse) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Rotate when mouse is moved left or right.";
      details_atomName = "moveRotateMouse";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Rotate Mouse";
      segmentbehaviorFields = "1";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField(turnSpeed, \"Turn rate (in degrees per pixel moved)\", float, 1.0);";
      segmentkeepAll = "21";
      segmentkeepAll_0 = "function moveRotateMouse::doRotate(%this, %worldPos)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_10 = "   ";
      segmentkeepAll_11 = "   %vector = t2dVectorSub( %newPos, %oldPos );";
      segmentkeepAll_12 = "   ";
      segmentkeepAll_13 = "   %deltaX = getWord( %vector , 0 );";
      segmentkeepAll_14 = "   ";
      segmentkeepAll_15 = "   %deltaX = %deltaX * %this.turnSpeed;";
      segmentkeepAll_16 = "   ";
      segmentkeepAll_17 = "   %currentAngle = %this.owner.getRotation();";
      segmentkeepAll_18 = "   ";
      segmentkeepAll_19 = "   %this.owner.setRotation(%currentAngle + %deltaX);";
      segmentkeepAll_2 = "   if(%this.lastPos $= \"\") ";
      segmentkeepAll_20 = "}";
      segmentkeepAll_3 = "   {";
      segmentkeepAll_4 = "      %this.lastPos = %worldPos;";
      segmentkeepAll_5 = "   }";
      segmentkeepAll_6 = "   ";
      segmentkeepAll_7 = "   %newPos = %worldPos;   ";
      segmentkeepAll_8 = "   %oldPos = %this.lastPos;";
      segmentkeepAll_9 = "   %this.lastPos = %newPos;";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDragged = "2";
      segmentonMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonMouseDragged_1 = "   %this.doRotate( %worldPos );";
      segmentonMouseMove = "2";
      segmentonMouseMove_0 = "   if (!%this.enable) return;";
      segmentonMouseMove_1 = "   %this.doRotate( %worldPos );";
      segmentonRightMouseDragged = "2";
      segmentonRightMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDragged_1 = "   %this.doRotate( %worldPos );";
      segments = "behaviorFields\tonAddToScene\tonMouseMove\tonMouseDragged\tonRightMouseDragged\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveGoToRightMouseClick) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Move to position where right mouse click occurs.";
      details_atomName = "moveGoToRightMouseClick";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Go to right mouse click";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonRightMouseDown = "2";
      segmentonRightMouseDown_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDown_1 = "   %this.owner.setPosition(%worldPos.x , %worldPos.y);";
      segments = "onAddToScene\tonRightMouseDown";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveGoToMouseClick) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Move to position where mouse click occurs.";
      details_atomName = "moveGoToMouseClick";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Go to mouse click";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDown = "2";
      segmentonMouseDown_0 = "   if (!%this.enable) return;";
      segmentonMouseDown_1 = "   %this.owner.setPosition(%worldPos.x , %worldPos.y);";
      segments = "onAddToScene\tonMouseDown";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveFollowMouse) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Follow the mouse position.";
      details_atomName = "moveFollowMouse";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Follow Mouse";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDragged = "2";
      segmentonMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonMouseDragged_1 = "   %this.owner.setPosition(%worldPos.x , %worldPos.y);";
      segmentonMouseMove = "2";
      segmentonMouseMove_0 = "   if (!%this.enable) return;";
      segmentonMouseMove_1 = "   %this.owner.setPosition(%worldPos.x , %worldPos.y);";
      segmentonRightMouseDragged = "2";
      segmentonRightMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDragged_1 = "   %this.owner.setPosition(%worldPos.x , %worldPos.y);";
      segments = "onAddToScene\tonMouseMove\tonMouseDragged\tonRightMouseDragged";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveFaceRightMouseClickDrag) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Face the mouse when it is right clicked and dragged.";
      details_atomName = "moveFaceRightMouseClickDrag";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Face Right Mouse Click and Drag";
      segmentkeepAll = "8";
      segmentkeepAll_0 = "function moveFaceRightMouseClickDrag::doFace(%this, %worldPos)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_2 = "   %position = %this.owner.getPosition();";
      segmentkeepAll_3 = "   %vector = t2dVectorSub( %worldPos, %position );";
      segmentkeepAll_4 = "   %normVec = t2dVectorNormalise( %vector );";
      segmentkeepAll_5 = "   %angle = vectorToAngle( %normVec );";
      segmentkeepAll_6 = "   %this.owner.setRotation( %angle );";
      segmentkeepAll_7 = "}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonRightMouseDown = "2";
      segmentonRightMouseDown_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDown_1 = "   %this.doFace( %worldPos );";
      segmentonRightMouseDragged = "2";
      segmentonRightMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDragged_1 = "   %this.doFace( %worldPos );";
      segments = "onAddToScene\tonRightMouseDown\tonRightMouseDragged\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveFaceRightMouseClick) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Face the mouse when it is right clicked.";
      details_atomName = "moveFaceRightMouseClick";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Face Right Mouse Click";
      segmentkeepAll = "8";
      segmentkeepAll_0 = "function moveFaceRightMouseClick::doFace(%this, %worldPos)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_2 = "   %position = %this.owner.getPosition();";
      segmentkeepAll_3 = "   %vector = t2dVectorSub( %worldPos, %position );";
      segmentkeepAll_4 = "   %normVec = t2dVectorNormalise( %vector );";
      segmentkeepAll_5 = "   %angle = vectorToAngle( %normVec );";
      segmentkeepAll_6 = "   %this.owner.setRotation( %angle );";
      segmentkeepAll_7 = "}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonRightMouseDown = "2";
      segmentonRightMouseDown_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDown_1 = "   %this.doFace( %worldPos );";
      segments = "onAddToScene\tonRightMouseDown\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveFaceMouseClickDrag) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Face the mouse when it is clicked and dragged.";
      details_atomName = "moveFaceMouseClickDrag";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Face Mouse Click and Drag";
      segmentkeepAll = "8";
      segmentkeepAll_0 = "function moveFaceMouseClickDrag::doFace(%this, %worldPos)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_2 = "   %position = %this.owner.getPosition();";
      segmentkeepAll_3 = "   %vector = t2dVectorSub( %worldPos, %position );";
      segmentkeepAll_4 = "   %normVec = t2dVectorNormalise( %vector );";
      segmentkeepAll_5 = "   %angle = vectorToAngle( %normVec );";
      segmentkeepAll_6 = "   %this.owner.setRotation( %angle );";
      segmentkeepAll_7 = "}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDown = "2";
      segmentonMouseDown_0 = "   if (!%this.enable) return;";
      segmentonMouseDown_1 = "   %this.doFace( %worldPos );";
      segmentonMouseDragged = "2";
      segmentonMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonMouseDragged_1 = "   %this.doFace( %worldPos );";
      segments = "onAddToScene\tonMouseDown\tonMouseDragged\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveFaceMouseClick) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Face the mouse when it is clicked.";
      details_atomName = "moveFaceMouseClick";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Face Mouse Click";
      segmentkeepAll = "8";
      segmentkeepAll_0 = "function moveFaceMouseClick::doFace(%this, %worldPos)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_2 = "   %position = %this.owner.getPosition();";
      segmentkeepAll_3 = "   %vector = t2dVectorSub( %worldPos, %position );";
      segmentkeepAll_4 = "   %normVec = t2dVectorNormalise( %vector );";
      segmentkeepAll_5 = "   %angle = vectorToAngle( %normVec );";
      segmentkeepAll_6 = "   %this.owner.setRotation( %angle );";
      segmentkeepAll_7 = "}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDown = "2";
      segmentonMouseDown_0 = "   if (!%this.enable) return;";
      segmentonMouseDown_1 = "   %this.doFace( %worldPos );";
      segments = "onAddToScene\tonMouseDown\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Mouse_moveFaceMouse) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Mouse Movements";
      description = "Follow the mouse position.";
      details_atomName = "moveFaceMouse";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Mouse";
      friendlyName = "Face Mouse";
      segmentkeepAll = "8";
      segmentkeepAll_0 = "function moveFaceMouse::doFace(%this, %worldPos)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_2 = "   %position = %this.owner.getPosition();";
      segmentkeepAll_3 = "   %vector = t2dVectorSub( %worldPos, %position );";
      segmentkeepAll_4 = "   %normVec = t2dVectorNormalise( %vector );";
      segmentkeepAll_5 = "   %angle = vectorToAngle( %normVec );";
      segmentkeepAll_6 = "   %this.owner.setRotation( %angle );";
      segmentkeepAll_7 = "}";
      segmentonAddToScene = "3";
      segmentonAddToScene_0 = "   %this.owner.setUseMouseEvents(true);";
      segmentonAddToScene_1 = "   %this.owner.setMouseLocked(true);";
      segmentonAddToScene_2 = "   sceneWindow2D.setUseObjectMouseEvents(1);";
      segmentonMouseDragged = "2";
      segmentonMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonMouseDragged_1 = "   %this.doFace( %worldPos );";
      segmentonMouseMove = "2";
      segmentonMouseMove_0 = "   if (!%this.enable) return;";
      segmentonMouseMove_1 = "   %this.doFace( %worldPos );";
      segmentonRightMouseDragged = "2";
      segmentonRightMouseDragged_0 = "   if (!%this.enable) return;";
      segmentonRightMouseDragged_1 = "   %this.doFace( %worldPos );";
      segments = "onAddToScene\tonMouseMove\tonMouseDragged\tonRightMouseDragged\tkeepAll";
};
//--- OBJECT WRITE END ---
