//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Game_gameSpaceInvaders_m) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Game Movements (Key/Joy/Con; Multibind)";
      description = "Move like player ship in Space Invaders";
      details_atomName = "gameSpaceInvaders_m";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Game";
      friendlyName = "Game: Space Invaders (multi)";
      segmentbehaviorFields = "5";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField(enable, \"Enable this behavior.\", bool, true);";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField(debugMode, \"Enable debugging output for this behavior.\", bool, false);";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Speed\", \"Movement Speed\", float, 50 );   ";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"Left\",  \"Move Left\",  keybind, \"Keyboard A\" );";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"Right\", \"Move Right\", keybind, \"Keyboard D\" );";
      segmentkeepAll = "31";
      segmentkeepAll_0 = "function gameSpaceInvaders_m::onMoveLeft( %this , %val )";
      segmentkeepAll_1 = "{   ";
      segmentkeepAll_10 = "{   ";
      segmentkeepAll_11 = "   if(%this.debugMode)  echo(\"gameSpaceInvaders_m::onMoveRight( \", %val , \" ) \" );";
      segmentkeepAll_12 = "   %this.moveRight = %val;";
      segmentkeepAll_13 = "   if(!%val && %this.moveLeft) %val = -1; ";
      segmentkeepAll_14 = "   %this.inputX  = %val;";
      segmentkeepAll_15 = "   ";
      segmentkeepAll_16 = "   %this.doMove();";
      segmentkeepAll_17 = "}";
      segmentkeepAll_18 = "function gameSpaceInvaders_m::onMoveJoystickLeftRight( %this , %val )";
      segmentkeepAll_19 = "{   ";
      segmentkeepAll_2 = "   if(%this.debugMode) echo(\"gameSpaceInvaders_m::onMoveLeft( \", %val , \" ) \" );";
      segmentkeepAll_20 = "   if(%this.debugMode)  echo(\"gameSpaceInvaders_m::onMoveJoystickLeftRight( \", %val , \" ) \" );";
      segmentkeepAll_21 = "   if( %val < 0 ) %this.inputX = %val;";
      segmentkeepAll_22 = "   else if (%val > 0) %this.inputX = %val;";
      segmentkeepAll_23 = "   else  %this.inputX = 0;";
      segmentkeepAll_24 = "   %this.doMove();";
      segmentkeepAll_25 = "}";
      segmentkeepAll_26 = "function gameSpaceInvaders_m::doMove( %this )";
      segmentkeepAll_27 = "{   ";
      segmentkeepAll_28 = "   %this.owner.setLinearVelocity( %this.inputX * %this.Speed, ";
      segmentkeepAll_29 = "                                  -%this.inputY * %this.Speed );";
      segmentkeepAll_3 = "   %this.moveLeft = %val;";
      segmentkeepAll_30 = "}";
      segmentkeepAll_4 = "   if(!%val && %this.moveRight) %val = 1;";
      segmentkeepAll_5 = "   else %val = -%val; ";
      segmentkeepAll_6 = "   %this.inputX  = %val;";
      segmentkeepAll_7 = "   %this.doMove();";
      segmentkeepAll_8 = "}";
      segmentkeepAll_9 = "function gameSpaceInvaders_m::onMoveRight( %this , %val )";
      segmentonAddToScene = "19";
      segmentonAddToScene_0 = "   if(%this.debugMode) echo(\"gameSpaceInvaders_m::onAddToScene( \", ((%this.getName() $= \"\") ? %this : %this.getName()) , \" ) @ \", getSimTime() );";
      segmentonAddToScene_1 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonAddToScene_10 = "   {";
      segmentonAddToScene_11 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_12 = "      moveMap.bindMulti( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonAddToScene_13 = "   }";
      segmentonAddToScene_14 = "  ";
      segmentonAddToScene_15 = "   %this.inputX = 0;";
      segmentonAddToScene_16 = "   %this.inputY = 0;";
      segmentonAddToScene_17 = "   %this.left   = 0;";
      segmentonAddToScene_18 = "   %this.right  = 0;";
      segmentonAddToScene_2 = "   // Ex: If you use joystick yaxis for left, use it for right too.";
      segmentonAddToScene_3 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_4 = "   {";
      segmentonAddToScene_5 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_6 = "      moveMap.bindMulti( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonAddToScene_7 = "      moveMap.bindMulti( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonAddToScene_8 = "   }";
      segmentonAddToScene_9 = "   else";
      segmentonRemoveFromScene = "14";
      segmentonRemoveFromScene_0 = "   if(!isObject(moveMap)) return;";
      segmentonRemoveFromScene_1 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonRemoveFromScene_10 = "   {";
      segmentonRemoveFromScene_11 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_12 = "      moveMap.unbindMulti( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonRemoveFromScene_13 = "   }";
      segmentonRemoveFromScene_2 = "   // Ex: If you use joystick yaxis for left, use it for right too.";
      segmentonRemoveFromScene_3 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_4 = "   {";
      segmentonRemoveFromScene_5 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_6 = "      moveMap.unbindMulti( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonRemoveFromScene_7 = "      moveMap.unbindMulti( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonRemoveFromScene_8 = "   }";
      segmentonRemoveFromScene_9 = "   else";
      segments = "behaviorFields\tonAddToScene\tonRemoveFromScene\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Game_gamePong_m) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Game Movements (Key/Joy/Con; Multibind)";
      description = "Move like player paddle in Pong";
      details_atomName = "gamePong_m";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Game";
      friendlyName = "Game: Pong (multi)";
      segmentbehaviorFields = "3";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Speed\", \"Movement Speed\", float, 50 );   ";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Up\",    \"Move Up\",    keybind, \"Keyboard W\" );";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Down\",  \"Move Down\",  keybind, \"Keyboard S\" );";
      segmentkeepAll = "32";
      segmentkeepAll_0 = "function gamePong_m::onMoveUp( %this , %val )";
      segmentkeepAll_1 = "{   ";
      segmentkeepAll_10 = "   if(%this.debugMode) echo(\"gamePong_m::onMoveDown( \", %val , \" ) \" );";
      segmentkeepAll_11 = "   %this.moveDown = %val;";
      segmentkeepAll_12 = "   if(!%val && %this.moveUp) %val = 1;";
      segmentkeepAll_13 = "   else %val = -%val; ";
      segmentkeepAll_14 = "   %this.inputY  = %val;";
      segmentkeepAll_15 = "   ";
      segmentkeepAll_16 = "   %this.doMove();";
      segmentkeepAll_17 = "}";
      segmentkeepAll_18 = "function gamePong_m::onMoveJoystickUpDown( %this , %val )";
      segmentkeepAll_19 = "{   ";
      segmentkeepAll_2 = "   if(%this.debugMode) echo(\"gamePong_m::onMoveUp( \", %val , \" ) \" );";
      segmentkeepAll_20 = "   if(%this.debugMode) echo(\"gamePong_m::onMoveJoystickUpDown( \", %val , \" ) \" );";
      segmentkeepAll_21 = "   if( %val < 0 ) %this.inputY = -%val;";
      segmentkeepAll_22 = "   else if (%val > 0) %this.inputY = -%val;";
      segmentkeepAll_23 = "   else %this.inputY = 0;";
      segmentkeepAll_24 = "   ";
      segmentkeepAll_25 = "   %this.doMove();";
      segmentkeepAll_26 = "}";
      segmentkeepAll_27 = "function gamePong_m::doMove( %this )";
      segmentkeepAll_28 = "{   ";
      segmentkeepAll_29 = "   %this.owner.setLinearVelocity( %this.inputX * %this.Speed, ";
      segmentkeepAll_3 = "   %this.moveUp = %val;";
      segmentkeepAll_30 = "                                  -%this.inputY * %this.Speed );";
      segmentkeepAll_31 = "}";
      segmentkeepAll_4 = "   if(!%val && %this.moveDown) %val = -1; ";
      segmentkeepAll_5 = "   %this.inputY  = %val;";
      segmentkeepAll_6 = "   %this.doMove();";
      segmentkeepAll_7 = "}";
      segmentkeepAll_8 = "function gamePong_m::onMoveDown( %this , %val )";
      segmentkeepAll_9 = "{   ";
      segmentonAddToScene = "17";
      segmentonAddToScene_0 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonAddToScene_1 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonAddToScene_10 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_11 = "      moveMap.bindMulti( getWord( %this.Up , 0 ), getWord( %this.Up , 1 ), %this, \"onMoveJoystickUpDown\" );";
      segmentonAddToScene_12 = "   }";
      segmentonAddToScene_13 = "   %this.inputX = 0;";
      segmentonAddToScene_14 = "   %this.inputY = 0;";
      segmentonAddToScene_15 = "   %this.up     = 0;";
      segmentonAddToScene_16 = "   %this.down   = 0;";
      segmentonAddToScene_2 = "   if( strstr( getWord( %this.Up , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_3 = "   {";
      segmentonAddToScene_4 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_5 = "      moveMap.bindMulti( getWord( %this.Up , 0 ),    getWord( %this.Up , 1 ),    %this, \"onMoveUp\" );";
      segmentonAddToScene_6 = "      moveMap.bindMulti( getWord( %this.Down , 0 ),  getWord( %this.Down , 1 ),  %this, \"onMoveDown\" );";
      segmentonAddToScene_7 = "   }";
      segmentonAddToScene_8 = "   else";
      segmentonAddToScene_9 = "   {";
      segmentonRemoveFromScene = "14";
      segmentonRemoveFromScene_0 = "   if(!isObject(moveMap)) return;";
      segmentonRemoveFromScene_1 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonRemoveFromScene_10 = "   {";
      segmentonRemoveFromScene_11 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_12 = "      moveMap.unbindMultiEvent( getWord( %this.Up , 0 ), getWord( %this.Up , 1 ), %this, \"onMoveJoystickUpDown\" );";
      segmentonRemoveFromScene_13 = "   }";
      segmentonRemoveFromScene_2 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonRemoveFromScene_3 = "   if( strstr( getWord( %this.Up , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_4 = "   {";
      segmentonRemoveFromScene_5 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_6 = "      moveMap.unbindMultiEvent( getWord( %this.Up , 0 ),    getWord( %this.Up , 1 ),    %this, \"onMoveUp\" );";
      segmentonRemoveFromScene_7 = "      moveMap.unbindMultiEvent( getWord( %this.Down , 0 ),  getWord( %this.Down , 1 ),  %this, \"onMoveDown\" );";
      segmentonRemoveFromScene_8 = "   }";
      segmentonRemoveFromScene_9 = "   else";
      segments = "behaviorFields\tonAddToScene\tonRemoveFromScene\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Game_gameParatrooper_m) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Game Movements (Key/Joy/Con; Multibind)";
      description = "Move like player turret in Paratroopers";
      details_atomName = "gameParatrooper_m";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Game";
      friendlyName = "Game: Paratrooper (multi)";
      segmentbehaviorFields = "5";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"rotateRate\", \"Rotation rate in degrees.\", float, 90 );   ";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Left\",  \"Move Left\",  keybind, \"Keyboard A\" );";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Right\", \"Move Right\", keybind, \"Keyboard D\" );";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"minAngle\", \"Minimum counterclockwise rotation angle.\", float, -85 );   ";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"maxAngle\", \"Maximum clockwise rotation angle.\", float, 85 );   ";
      segmentkeepAll = "42";
      segmentkeepAll_0 = "function gameParatrooper_m::onMoveLeft( %this , %val )";
      segmentkeepAll_1 = "{   ";
      segmentkeepAll_10 = "{   ";
      segmentkeepAll_11 = "   if(%this.debugMode) echo(\"gameParatrooper_m::onMoveRight( \", %val , \" ) \" );";
      segmentkeepAll_12 = "   %this.moveRight = %val;";
      segmentkeepAll_13 = "   if(!%val && %this.moveLeft) %val = -1; ";
      segmentkeepAll_14 = "   %this.inputX  = %val;";
      segmentkeepAll_15 = "   ";
      segmentkeepAll_16 = "   %this.doMove();";
      segmentkeepAll_17 = "}";
      segmentkeepAll_18 = "function gameParatrooper_m::onMoveJoystickLeftRight( %this , %val )";
      segmentkeepAll_19 = "{   ";
      segmentkeepAll_2 = "   if(%this.debugMode) echo(\"gameParatrooper_m::onMoveLeft( \", %val , \" ) \" );";
      segmentkeepAll_20 = "   if(%this.debugMode) echo(\"gameParatrooper_m::onMoveJoystickLeftRight( \", %val , \" ) \" );";
      segmentkeepAll_21 = "   if( %val < 0 ) %this.inputX = %val;";
      segmentkeepAll_22 = "   else if (%val > 0) %this.inputX = %val;";
      segmentkeepAll_23 = "   else  %this.inputX = 0;";
      segmentkeepAll_24 = "   %this.doMove();";
      segmentkeepAll_25 = "}";
      segmentkeepAll_26 = "function gameParatrooper_m::doMove( %this )";
      segmentkeepAll_27 = "{   ";
      segmentkeepAll_28 = "   // if using limited-rotation, rotate to the min or max angle";
      segmentkeepAll_29 = "   if( %this.inputX < 0 ) ";
      segmentkeepAll_3 = "   %this.moveLeft = %val;";
      segmentkeepAll_30 = "   {";
      segmentkeepAll_31 = "      %this.owner.rotateTo( %this.minAngle , %this.rotateRate, true  ); ";
      segmentkeepAll_32 = "   }";
      segmentkeepAll_33 = "   else if ( %this.inputX > 0 ) ";
      segmentkeepAll_34 = "   {";
      segmentkeepAll_35 = "      %this.owner.rotateTo( %this.maxAngle , %this.rotateRate, true  ); ";
      segmentkeepAll_36 = "   } ";
      segmentkeepAll_37 = "   else";
      segmentkeepAll_38 = "   {";
      segmentkeepAll_39 = "      %this.owner.setAngularVelocity( 0 );";
      segmentkeepAll_4 = "   if(!%val && %this.moveRight) %val = 1;";
      segmentkeepAll_40 = "   }";
      segmentkeepAll_41 = "}";
      segmentkeepAll_5 = "   else %val = -%val; ";
      segmentkeepAll_6 = "   %this.inputX  = %val;";
      segmentkeepAll_7 = "   %this.doMove();";
      segmentkeepAll_8 = "}";
      segmentkeepAll_9 = "function gameParatrooper_m::onMoveRight( %this , %val )";
      segmentonAddToScene = "17";
      segmentonAddToScene_0 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonAddToScene_1 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonAddToScene_10 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_11 = "      moveMap.bindMulti( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonAddToScene_12 = "   }";
      segmentonAddToScene_13 = "  ";
      segmentonAddToScene_14 = "   %this.inputX = 0;";
      segmentonAddToScene_15 = "   %this.left   = 0;";
      segmentonAddToScene_16 = "   %this.right  = 0;";
      segmentonAddToScene_2 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_3 = "   {";
      segmentonAddToScene_4 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_5 = "      moveMap.bindMulti( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonAddToScene_6 = "      moveMap.bindMulti( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonAddToScene_7 = "   }";
      segmentonAddToScene_8 = "   else";
      segmentonAddToScene_9 = "   {";
      segmentonRemoveFromScene = "14";
      segmentonRemoveFromScene_0 = "   if(!isObject(moveMap)) return;";
      segmentonRemoveFromScene_1 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonRemoveFromScene_10 = "   {";
      segmentonRemoveFromScene_11 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_12 = "      moveMap.unbindMultiEvent( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonRemoveFromScene_13 = "   }";
      segmentonRemoveFromScene_2 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonRemoveFromScene_3 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_4 = "   {";
      segmentonRemoveFromScene_5 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_6 = "      moveMap.unbindMultiEvent( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonRemoveFromScene_7 = "      moveMap.unbindMultiEvent( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonRemoveFromScene_8 = "   }";
      segmentonRemoveFromScene_9 = "   else";
      segments = "behaviorFields\tonAddToScene\tonRemoveFromScene\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Game_gameGeometryWars_m) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Game Movements (Key/Joy/Con; Multibind)";
      description = "Move like player ship in Geometry Wars";
      details_atomName = "gameGeometryWars_m";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Game";
      friendlyName = "Game: Geometry Wars (multi)";
      segmentbehaviorFields = "5";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Speed\", \"Movement Speed\", float, 50 );   ";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Up\",    \"Move Up\",    keybind, \"Keyboard W\" );";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Down\",  \"Move Down\",  keybind, \"Keyboard S\" );";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"Left\",  \"Move Left\",  keybind, \"Keyboard A\" );";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"Right\", \"Move Right\", keybind, \"Keyboard D\" );";
      segmentkeepAll = "61";
      segmentkeepAll_0 = "function gameGeometryWars_m::onMoveUp( %this , %val )";
      segmentkeepAll_1 = "{   ";
      segmentkeepAll_10 = "   if(%this.debugMode) echo(\"gameGeometryWars_m::onMoveDown( \", %val , \" ) \" );";
      segmentkeepAll_11 = "   %this.moveDown = %val;";
      segmentkeepAll_12 = "   if(!%val && %this.moveUp) %val = 1;";
      segmentkeepAll_13 = "   else %val = -%val; ";
      segmentkeepAll_14 = "   %this.inputY  = %val;";
      segmentkeepAll_15 = "   ";
      segmentkeepAll_16 = "   %this.doMove();";
      segmentkeepAll_17 = "}";
      segmentkeepAll_18 = "function gameGeometryWars_m::onMoveJoystickUpDown( %this , %val )";
      segmentkeepAll_19 = "{   ";
      segmentkeepAll_2 = "   if(%this.debugMode) echo(\"gameGeometryWars_m::onMoveUp( \", %val , \" ) \" );";
      segmentkeepAll_20 = "   if(%this.debugMode) echo(\"gameGeometryWars_m::onMoveJoystickUpDown( \", %val , \" ) \" );";
      segmentkeepAll_21 = "   if( %val < 0 ) %this.inputY = -%val;";
      segmentkeepAll_22 = "   else if (%val > 0) %this.inputY = -%val;";
      segmentkeepAll_23 = "   else %this.inputY = 0;";
      segmentkeepAll_24 = "   ";
      segmentkeepAll_25 = "   %this.doMove();";
      segmentkeepAll_26 = "}";
      segmentkeepAll_27 = "function gameGeometryWars_m::onMoveLeft( %this , %val )";
      segmentkeepAll_28 = "{   ";
      segmentkeepAll_29 = "   if(%this.debugMode) echo(\"gameGeometryWars_m::onMoveLeft( \", %val , \" ) \" );";
      segmentkeepAll_3 = "   %this.moveUp = %val;";
      segmentkeepAll_30 = "   %this.moveLeft = %val;";
      segmentkeepAll_31 = "   if(!%val && %this.moveRight) %val = 1;";
      segmentkeepAll_32 = "   else %val = -%val; ";
      segmentkeepAll_33 = "   %this.inputX  = %val;";
      segmentkeepAll_34 = "   %this.doMove();";
      segmentkeepAll_35 = "}";
      segmentkeepAll_36 = "function gameGeometryWars_m::onMoveRight( %this , %val )";
      segmentkeepAll_37 = "{   ";
      segmentkeepAll_38 = "   if(%this.debugMode) echo(\"gameGeometryWars_m::onMoveRight( \", %val , \" ) \" );";
      segmentkeepAll_39 = "   %this.moveRight = %val;";
      segmentkeepAll_4 = "   if(!%val && %this.moveDown) %val = -1; ";
      segmentkeepAll_40 = "   if(!%val && %this.moveLeft) %val = -1; ";
      segmentkeepAll_41 = "   %this.inputX  = %val;";
      segmentkeepAll_42 = "   ";
      segmentkeepAll_43 = "   %this.doMove();";
      segmentkeepAll_44 = "}";
      segmentkeepAll_45 = "function gameGeometryWars_m::onMoveJoystickLeftRight( %this , %val )";
      segmentkeepAll_46 = "{   ";
      segmentkeepAll_47 = "   if(%this.debugMode) echo(\"gameGeometryWars_m::onMoveJoystickLeftRight( \", %val , \" ) \" );";
      segmentkeepAll_48 = "   if( %val < 0 ) %this.inputX = %val;";
      segmentkeepAll_49 = "   else if (%val > 0) %this.inputX = %val;";
      segmentkeepAll_5 = "   %this.inputY  = %val;";
      segmentkeepAll_50 = "   else  %this.inputX = 0;";
      segmentkeepAll_51 = "   %this.doMove();";
      segmentkeepAll_52 = "}";
      segmentkeepAll_53 = "function gameGeometryWars_m::doMove( %this )";
      segmentkeepAll_54 = "{   ";
      segmentkeepAll_55 = "   %this.owner.setLinearVelocity( %this.inputX * %this.Speed, ";
      segmentkeepAll_56 = "                                  -%this.inputY * %this.Speed );";
      segmentkeepAll_57 = "   if(!%this.inputX && !%this.inputY) return;";
      segmentkeepAll_58 = "   %facingAngle = vectorToAngle( %this.inputX SPC -%this.inputY );";
      segmentkeepAll_59 = "   %this.owner.setRotation(%facingAngle);";
      segmentkeepAll_6 = "   %this.doMove();";
      segmentkeepAll_60 = "}";
      segmentkeepAll_7 = "}";
      segmentkeepAll_8 = "function gameGeometryWars_m::onMoveDown( %this , %val )";
      segmentkeepAll_9 = "{   ";
      segmentonAddToScene = "31";
      segmentonAddToScene_0 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonAddToScene_1 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonAddToScene_10 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_11 = "      moveMap.bindMulti( getWord( %this.Up , 0 ), getWord( %this.Up , 1 ), %this, \"onMoveJoystickUpDown\" );";
      segmentonAddToScene_12 = "   }";
      segmentonAddToScene_13 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_14 = "   {";
      segmentonAddToScene_15 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_16 = "      moveMap.bindMulti( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonAddToScene_17 = "      moveMap.bindMulti( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonAddToScene_18 = "   }";
      segmentonAddToScene_19 = "   else";
      segmentonAddToScene_2 = "   if( strstr( getWord( %this.Up , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_20 = "   {";
      segmentonAddToScene_21 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_22 = "      moveMap.bindMulti( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonAddToScene_23 = "   }";
      segmentonAddToScene_24 = "  ";
      segmentonAddToScene_25 = "   %this.inputX = 0;";
      segmentonAddToScene_26 = "   %this.inputY = 0;";
      segmentonAddToScene_27 = "   %this.up     = 0;";
      segmentonAddToScene_28 = "   %this.down   = 0;";
      segmentonAddToScene_29 = "   %this.left   = 0;";
      segmentonAddToScene_3 = "   {";
      segmentonAddToScene_30 = "   %this.right  = 0;";
      segmentonAddToScene_4 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_5 = "      moveMap.bindMulti( getWord( %this.Up , 0 ),    getWord( %this.Up , 1 ),    %this, \"onMoveUp\" );";
      segmentonAddToScene_6 = "      moveMap.bindMulti( getWord( %this.Down , 0 ),  getWord( %this.Down , 1 ),  %this, \"onMoveDown\" );";
      segmentonAddToScene_7 = "   }";
      segmentonAddToScene_8 = "   else";
      segmentonAddToScene_9 = "   {";
      segmentonRemoveFromScene = "25";
      segmentonRemoveFromScene_0 = "   if(!isObject(moveMap)) return;";
      segmentonRemoveFromScene_1 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonRemoveFromScene_10 = "   {";
      segmentonRemoveFromScene_11 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_12 = "      moveMap.unbindMultiEvent( getWord( %this.Up , 0 ), getWord( %this.Up , 1 ), %this, \"onMoveJoystickUpDown\" );";
      segmentonRemoveFromScene_13 = "   }";
      segmentonRemoveFromScene_14 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_15 = "   {";
      segmentonRemoveFromScene_16 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_17 = "      moveMap.unbindMultiEvent( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonRemoveFromScene_18 = "      moveMap.unbindMultiEvent( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonRemoveFromScene_19 = "   }";
      segmentonRemoveFromScene_2 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonRemoveFromScene_20 = "   else";
      segmentonRemoveFromScene_21 = "   {";
      segmentonRemoveFromScene_22 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_23 = "      moveMap.unbindMultiEvent( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonRemoveFromScene_24 = "   }";
      segmentonRemoveFromScene_3 = "   if( strstr( getWord( %this.Up , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_4 = "   {";
      segmentonRemoveFromScene_5 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_6 = "      moveMap.unbindMultiEvent( getWord( %this.Up , 0 ),    getWord( %this.Up , 1 ),    %this, \"onMoveUp\" );";
      segmentonRemoveFromScene_7 = "      moveMap.unbindMultiEvent( getWord( %this.Down , 0 ),  getWord( %this.Down , 1 ),  %this, \"onMoveDown\" );";
      segmentonRemoveFromScene_8 = "   }";
      segmentonRemoveFromScene_9 = "   else";
      segments = "behaviorFields\tonAddToScene\tonRemoveFromScene\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Game_gameAsteroids_m) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Game Movements (Key/Joy/Con; Multibind)";
      description = "Move like player ship in Asteroids";
      details_atomName = "gameAsteroids_m";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Game";
      friendlyName = "Game: Asteroids (multi)";
      segmentbehaviorFields = "9";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Thrust\", \"Thrusting power.\", float, 100 );  ";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"RotationRate\", \"Rotation speed.\", float, 135 );   ";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"MaxSpeed\", \"Maximum speed.\", float, 35 );   ";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"Damping\", \"Reduce speed by this percentage each second.\", float, 0.3 );   ";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"Up\",    \"Move Up\",    keybind, \"Keyboard W\" );";
      segmentbehaviorFields_5 = "   %behavior.addBehaviorField( \"Left\",  \"Move Left\",  keybind, \"Keyboard A\" );";
      segmentbehaviorFields_6 = "   %behavior.addBehaviorField( \"Right\", \"Move Right\", keybind, \"Keyboard D\" );";
      segmentbehaviorFields_7 = "   %behavior.addBehaviorField( \"EnableStop\", \"Allow instant stops.\", bool, false);";
      segmentbehaviorFields_8 = "   %behavior.addBehaviorField( \"Stop\",  \"Stop moving.\",  keybind, \"Keyboard S\" );";
      segmentkeepAll = "78";
      segmentkeepAll_0 = "function gameAsteroids_m::onThrust( %this , %val )";
      segmentkeepAll_1 = "{   ";
      segmentkeepAll_10 = "   %this.doMove();";
      segmentkeepAll_11 = "}";
      segmentkeepAll_12 = "function gameAsteroids_m::onJoystickThrust( %this , %val )";
      segmentkeepAll_13 = "{   ";
      segmentkeepAll_14 = "   if(%this.debugMode) echo(\"gameAsteroids_m::onJoystickThrust( \", %val , \" ) \" );";
      segmentkeepAll_15 = "   if( %val < 0 ) %this.inputY = -%val; ";
      segmentkeepAll_16 = "   else %this.inputY = 0;";
      segmentkeepAll_17 = "   ";
      segmentkeepAll_18 = "   %this.doMove();";
      segmentkeepAll_19 = "}";
      segmentkeepAll_2 = "   if(%this.debugMode) echo(\"ForwardThrust::onThrust( \", %val , \" ) \" );";
      segmentkeepAll_20 = "function gameAsteroids_m::onJoystickStop( %this , %val )";
      segmentkeepAll_21 = "{   ";
      segmentkeepAll_22 = "   if(%this.debugMode) echo(\"gameAsteroids_m::onJoystickStop( \", %val , \" ) \" );";
      segmentkeepAll_23 = "   if( %val > 0 ) %this.stopAll = 1; ";
      segmentkeepAll_24 = "   else %this.stopAll = 0;";
      segmentkeepAll_25 = "   ";
      segmentkeepAll_26 = "   %this.doMove();";
      segmentkeepAll_27 = "}";
      segmentkeepAll_28 = "function gameAsteroids_m::onMoveLeft( %this , %val )";
      segmentkeepAll_29 = "{   ";
      segmentkeepAll_3 = "   %this.inputY  = %val;";
      segmentkeepAll_30 = "   if(%this.debugMode) echo(\"gameAsteroids_m::onMoveLeft( \", %val , \" ) \" );";
      segmentkeepAll_31 = "   %this.moveLeft = %val;";
      segmentkeepAll_32 = "   if(!%val && %this.moveRight) %val = 1;";
      segmentkeepAll_33 = "   else %val = -%val; ";
      segmentkeepAll_34 = "   %this.inputX  = %val;";
      segmentkeepAll_35 = "   %this.doMove();";
      segmentkeepAll_36 = "}";
      segmentkeepAll_37 = "function gameAsteroids_m::onMoveRight( %this , %val )";
      segmentkeepAll_38 = "{   ";
      segmentkeepAll_39 = "   if(%this.debugMode) echo(\"gameAsteroids_m::onMoveRight( \", %val , \" ) \" );";
      segmentkeepAll_4 = "   %this.doMove();";
      segmentkeepAll_40 = "   %this.moveRight = %val;";
      segmentkeepAll_41 = "   if(!%val && %this.moveLeft) %val = -1; ";
      segmentkeepAll_42 = "   %this.inputX  = %val;";
      segmentkeepAll_43 = "   ";
      segmentkeepAll_44 = "   %this.doMove();";
      segmentkeepAll_45 = "}";
      segmentkeepAll_46 = "function gameAsteroids_m::onMoveJoystickLeftRight( %this , %val )";
      segmentkeepAll_47 = "{   ";
      segmentkeepAll_48 = "   if(%this.debugMode) echo(\"gameAsteroids_m::onMoveJoystickLeftRight( \", %val , \" ) \" );";
      segmentkeepAll_49 = "   if( %val < 0 ) %this.inputX = %val;";
      segmentkeepAll_5 = "}";
      segmentkeepAll_50 = "   else if (%val > 0) %this.inputX = %val;";
      segmentkeepAll_51 = "   else  %this.inputX = 0;";
      segmentkeepAll_52 = "   %this.doMove();";
      segmentkeepAll_53 = "}";
      segmentkeepAll_54 = "function gameAsteroids_m::doMove( %this )";
      segmentkeepAll_55 = "{   ";
      segmentkeepAll_56 = "   if(%this.debugMode) echo(\"gameAsteroids_m::doMove( \", ((%this.getName() $= \"\") ? %this : %this.getName()) , \" ) @ \", getSimTime() );";
      segmentkeepAll_57 = "   if(%this.stopAll)";
      segmentkeepAll_58 = "   {";
      segmentkeepAll_59 = "      %this.owner.setAtRest();";
      segmentkeepAll_6 = "function gameAsteroids_m::onStop( %this , %val )";
      segmentkeepAll_60 = "   }";
      segmentkeepAll_61 = "   else";
      segmentkeepAll_62 = "   {";
      segmentkeepAll_63 = "      %thrustMagnitude = %this.inputY * %this.Thrust;";
      segmentkeepAll_64 = "      %this.owner.setAngularVelocity( %this.inputX * %this.RotationRate );";
      segmentkeepAll_65 = "      %this.owner.setConstantForcePolar( %this.owner.getRotation(), %thrustMagnitude , true );      ";
      segmentkeepAll_66 = "   } ";
      segmentkeepAll_67 = "   ";
      segmentkeepAll_68 = "    ";
      segmentkeepAll_69 = "   if( %this.inputX  || ";
      segmentkeepAll_7 = "{   ";
      segmentkeepAll_70 = "       %this.inputY  ||";
      segmentkeepAll_71 = "       %this.left    ||";
      segmentkeepAll_72 = "       %this.right   ||";
      segmentkeepAll_73 = "       %this.stopAll) ";
      segmentkeepAll_74 = "       {";
      segmentkeepAll_75 = "          %this.schedule(100, doMove);";
      segmentkeepAll_76 = "       }";
      segmentkeepAll_77 = "}";
      segmentkeepAll_8 = "   if(%this.debugMode) echo(\"ForwardThrust::onThrust( \", %val , \" ) \" );";
      segmentkeepAll_9 = "   %this.stopAll  = %val;";
      segmentonAddToScene = "44";
      segmentonAddToScene_0 = "   %this.owner.setMaxLinearVelocity(%this.MaxSpeed);";
      segmentonAddToScene_1 = "   %this.owner.setDamping(%this.Damping);";
      segmentonAddToScene_10 = "   {";
      segmentonAddToScene_11 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_12 = "      moveMap.bindMulti( getWord( %this.Up , 0 ), getWord( %this.Up , 1 ), %this, \"onJoystickThrust\" );";
      segmentonAddToScene_13 = "   }";
      segmentonAddToScene_14 = "   if(%this.EnableStop)";
      segmentonAddToScene_15 = "   {";
      segmentonAddToScene_16 = "      if( strstr( getWord( %this.Stop , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_17 = "      {";
      segmentonAddToScene_18 = "         // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_19 = "         moveMap.bindMulti( getWord( %this.Stop , 0 ),  getWord( %this.Stop , 1 ),    %this, \"onStop\" );";
      segmentonAddToScene_2 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonAddToScene_20 = "      }";
      segmentonAddToScene_21 = "      else";
      segmentonAddToScene_22 = "      {";
      segmentonAddToScene_23 = "         // USING JOYSTICK AXIS";
      segmentonAddToScene_24 = "         moveMap.bindMulti( getWord( %this.Stop , 0 ), getWord( %this.Stop , 1 ), %this, \"onJoystickStop\" );";
      segmentonAddToScene_25 = "      }";
      segmentonAddToScene_26 = "   }";
      segmentonAddToScene_27 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_28 = "   {";
      segmentonAddToScene_29 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_3 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonAddToScene_30 = "      moveMap.bindMulti( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonAddToScene_31 = "      moveMap.bindMulti( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonAddToScene_32 = "   }";
      segmentonAddToScene_33 = "   else";
      segmentonAddToScene_34 = "   {";
      segmentonAddToScene_35 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_36 = "      moveMap.bindMulti( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonAddToScene_37 = "   }";
      segmentonAddToScene_38 = "   ";
      segmentonAddToScene_39 = "   %this.inputX   = 0;";
      segmentonAddToScene_4 = "   if( strstr( getWord( %this.Up , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_40 = "   %this.inputY   = 0;";
      segmentonAddToScene_41 = "   %this.left     = 0;";
      segmentonAddToScene_42 = "   %this.right    = 0;";
      segmentonAddToScene_43 = "   %this.stopAll  = 0;";
      segmentonAddToScene_5 = "   {";
      segmentonAddToScene_6 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_7 = "      moveMap.bindMulti( getWord( %this.Up , 0 ),    getWord( %this.Up , 1 ),    %this, \"onThrust\" );";
      segmentonAddToScene_8 = "   }";
      segmentonAddToScene_9 = "   else";
      segmentonRemoveFromScene = "38";
      segmentonRemoveFromScene_0 = "  ";
      segmentonRemoveFromScene_1 = "   if(!isObject(moveMap)) return;";
      segmentonRemoveFromScene_10 = "   {";
      segmentonRemoveFromScene_11 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_12 = "      moveMap.unbindMultiEvent( getWord( %this.Up , 0 ), getWord( %this.Up , 1 ), %this, \"onJoystickThrust\" );";
      segmentonRemoveFromScene_13 = "   }";
      segmentonRemoveFromScene_14 = "   if(%this.EnableStop)";
      segmentonRemoveFromScene_15 = "   {";
      segmentonRemoveFromScene_16 = "      if( strstr( getWord( %this.Stop , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_17 = "      {";
      segmentonRemoveFromScene_18 = "         // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_19 = "         moveMap.unbindMultiEvent( getWord( %this.Stop , 0 ),  getWord( %this.Stop , 1 ),    %this, \"onStop\" );";
      segmentonRemoveFromScene_2 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonRemoveFromScene_20 = "      }";
      segmentonRemoveFromScene_21 = "      else";
      segmentonRemoveFromScene_22 = "      {";
      segmentonRemoveFromScene_23 = "         // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_24 = "         moveMap.unbindMultiEvent( getWord( %this.Stop , 0 ), getWord( %this.Stop , 1 ), %this, \"onJoystickStop\" );";
      segmentonRemoveFromScene_25 = "      }";
      segmentonRemoveFromScene_26 = "   }";
      segmentonRemoveFromScene_27 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_28 = "   {";
      segmentonRemoveFromScene_29 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_3 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonRemoveFromScene_30 = "      moveMap.unbindMultiEvent( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonRemoveFromScene_31 = "      moveMap.unbindMultiEvent( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonRemoveFromScene_32 = "   }";
      segmentonRemoveFromScene_33 = "   else";
      segmentonRemoveFromScene_34 = "   {";
      segmentonRemoveFromScene_35 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_36 = "      moveMap.unbindMultiEvent( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonRemoveFromScene_37 = "   }";
      segmentonRemoveFromScene_4 = "   if( strstr( getWord( %this.Up , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_5 = "   {";
      segmentonRemoveFromScene_6 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_7 = "      moveMap.unbindMultiEvent( getWord( %this.Up , 0 ),    getWord( %this.Up , 1 ),    %this, \"onThrust\" );";
      segmentonRemoveFromScene_8 = "   }";
      segmentonRemoveFromScene_9 = "   else";
      segments = "behaviorFields\tonAddToScene\tonRemoveFromScene\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_01MovementInput_Game_game1942_m) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "01 - Game Movements (Key/Joy/Con; Multibind)";
      description = "Move like player plane in 1942";
      details_atomName = "game1942_m";
      details_category = "01 - Movement (Input)";
      details_eventAction = "full";
      details_subCategory = "Game";
      friendlyName = "Game: 1942 (multi)";
      segmentbehaviorFields = "5";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Speed\", \"Movement Speed\", float, 50 );   ";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Up\",    \"Move Up\",    keybind, \"Keyboard W\" );";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Down\",  \"Move Down\",  keybind, \"Keyboard S\" );";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"Left\",  \"Move Left\",  keybind, \"Keyboard A\" );";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"Right\", \"Move Right\", keybind, \"Keyboard D\" );";
      segmentkeepAll = "58";
      segmentkeepAll_0 = "function game1942_m::onMoveUp( %this , %val )";
      segmentkeepAll_1 = "{   ";
      segmentkeepAll_10 = "   if(%this.debugMode) echo(\"game1942_m::onMoveDown( \", %val , \" ) \" );";
      segmentkeepAll_11 = "   %this.moveDown = %val;";
      segmentkeepAll_12 = "   if(!%val && %this.moveUp) %val = 1;";
      segmentkeepAll_13 = "   else %val = -%val; ";
      segmentkeepAll_14 = "   %this.inputY  = %val;";
      segmentkeepAll_15 = "   ";
      segmentkeepAll_16 = "   %this.doMove();";
      segmentkeepAll_17 = "}";
      segmentkeepAll_18 = "function game1942_m::onMoveJoystickUpDown( %this , %val )";
      segmentkeepAll_19 = "{   ";
      segmentkeepAll_2 = "   if(%this.debugMode) echo(\"game1942_m::onMoveUp( \", %val , \" ) \" );";
      segmentkeepAll_20 = "   if(%this.debugMode) echo(\"game1942_m::onMoveJoystickUpDown( \", %val , \" ) \" );";
      segmentkeepAll_21 = "   if( %val < 0 ) %this.inputY = -%val;";
      segmentkeepAll_22 = "   else if (%val > 0) %this.inputY = -%val;";
      segmentkeepAll_23 = "   else %this.inputY = 0;";
      segmentkeepAll_24 = "   ";
      segmentkeepAll_25 = "   %this.doMove();";
      segmentkeepAll_26 = "}";
      segmentkeepAll_27 = "function game1942_m::onMoveLeft( %this , %val )";
      segmentkeepAll_28 = "{   ";
      segmentkeepAll_29 = "   if(%this.debugMode) echo(\"game1942_m::onMoveLeft( \", %val , \" ) \" );";
      segmentkeepAll_3 = "   %this.moveUp = %val;";
      segmentkeepAll_30 = "   %this.moveLeft = %val;";
      segmentkeepAll_31 = "   if(!%val && %this.moveRight) %val = 1;";
      segmentkeepAll_32 = "   else %val = -%val; ";
      segmentkeepAll_33 = "   %this.inputX  = %val;";
      segmentkeepAll_34 = "   %this.doMove();";
      segmentkeepAll_35 = "}";
      segmentkeepAll_36 = "function game1942_m::onMoveRight( %this , %val )";
      segmentkeepAll_37 = "{   ";
      segmentkeepAll_38 = "   if(%this.debugMode) echo(\"game1942_m::onMoveRight( \", %val , \" ) \" );";
      segmentkeepAll_39 = "   %this.moveRight = %val;";
      segmentkeepAll_4 = "   if(!%val && %this.moveDown) %val = -1; ";
      segmentkeepAll_40 = "   if(!%val && %this.moveLeft) %val = -1; ";
      segmentkeepAll_41 = "   %this.inputX  = %val;";
      segmentkeepAll_42 = "   ";
      segmentkeepAll_43 = "   %this.doMove();";
      segmentkeepAll_44 = "}";
      segmentkeepAll_45 = "function game1942_m::onMoveJoystickLeftRight( %this , %val )";
      segmentkeepAll_46 = "{   ";
      segmentkeepAll_47 = "   if(%this.debugMode) echo(\"game1942_m::onMoveJoystickLeftRight( \", %val , \" ) \" );";
      segmentkeepAll_48 = "   if( %val < 0 ) %this.inputX = %val;";
      segmentkeepAll_49 = "   else if (%val > 0) %this.inputX = %val;";
      segmentkeepAll_5 = "   %this.inputY  = %val;";
      segmentkeepAll_50 = "   else  %this.inputX = 0;";
      segmentkeepAll_51 = "   %this.doMove();";
      segmentkeepAll_52 = "}";
      segmentkeepAll_53 = "function game1942_m::doMove( %this )";
      segmentkeepAll_54 = "{   ";
      segmentkeepAll_55 = "   %this.owner.setLinearVelocity( %this.inputX * %this.Speed, ";
      segmentkeepAll_56 = "                                  -%this.inputY * %this.Speed );";
      segmentkeepAll_57 = "}";
      segmentkeepAll_6 = "   %this.doMove();";
      segmentkeepAll_7 = "}";
      segmentkeepAll_8 = "function game1942_m::onMoveDown( %this , %val )";
      segmentkeepAll_9 = "{   ";
      segmentonAddToScene = "31";
      segmentonAddToScene_0 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonAddToScene_1 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonAddToScene_10 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_11 = "      moveMap.bindMulti( getWord( %this.Up , 0 ), getWord( %this.Up , 1 ), %this, \"onMoveJoystickUpDown\" );";
      segmentonAddToScene_12 = "   }";
      segmentonAddToScene_13 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_14 = "   {";
      segmentonAddToScene_15 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_16 = "      moveMap.bindMulti( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonAddToScene_17 = "      moveMap.bindMulti( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonAddToScene_18 = "   }";
      segmentonAddToScene_19 = "   else";
      segmentonAddToScene_2 = "   if( strstr( getWord( %this.Up , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_20 = "   {";
      segmentonAddToScene_21 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_22 = "      moveMap.bindMulti( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonAddToScene_23 = "   }";
      segmentonAddToScene_24 = "  ";
      segmentonAddToScene_25 = "   %this.inputX = 0;";
      segmentonAddToScene_26 = "   %this.inputY = 0;";
      segmentonAddToScene_27 = "   %this.moveUp     = 0;";
      segmentonAddToScene_28 = "   %this.moveDown   = 0;";
      segmentonAddToScene_29 = "   %this.moveLeft   = 0;";
      segmentonAddToScene_3 = "   {";
      segmentonAddToScene_30 = "   %this.moveRight  = 0;";
      segmentonAddToScene_4 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_5 = "      moveMap.bindMulti( getWord( %this.Up , 0 ),    getWord( %this.Up , 1 ),    %this, \"onMoveUp\" );";
      segmentonAddToScene_6 = "      moveMap.bindMulti( getWord( %this.Down , 0 ),  getWord( %this.Down , 1 ),  %this, \"onMoveDown\" );";
      segmentonAddToScene_7 = "   }";
      segmentonAddToScene_8 = "   else";
      segmentonAddToScene_9 = "   {";
      segmentonRemoveFromScene = "25";
      segmentonRemoveFromScene_0 = "   if(!isObject(moveMap)) return;";
      segmentonRemoveFromScene_1 = "   // Note: Do not use a joystick for only one part of a movement pair. ";
      segmentonRemoveFromScene_10 = "   {";
      segmentonRemoveFromScene_11 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_12 = "      moveMap.unbindMulti( getWord( %this.Up , 0 ), getWord( %this.Up , 1 ), %this, \"onMoveJoystickUpDown\" );";
      segmentonRemoveFromScene_13 = "   }";
      segmentonRemoveFromScene_14 = "   if( strstr( getWord( %this.Left , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_15 = "   {";
      segmentonRemoveFromScene_16 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_17 = "      moveMap.unbindMulti( getWord( %this.Left , 0 ),  getWord( %this.Left , 1 ),  %this, \"onMoveLeft\" );";
      segmentonRemoveFromScene_18 = "      moveMap.unbindMulti( getWord( %this.Right , 0 ), getWord( %this.Right , 1 ), %this, \"onMoveRight\" );";
      segmentonRemoveFromScene_19 = "   }";
      segmentonRemoveFromScene_2 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonRemoveFromScene_20 = "   else";
      segmentonRemoveFromScene_21 = "   {";
      segmentonRemoveFromScene_22 = "      // USING JOYSTICK AXIS";
      segmentonRemoveFromScene_23 = "      moveMap.unbindMulti( getWord( %this.Left , 0 ), getWord( %this.Left , 1 ), %this, \"onMoveJoystickLeftRight\" );";
      segmentonRemoveFromScene_24 = "   }";
      segmentonRemoveFromScene_3 = "   if( strstr( getWord( %this.Up , 1 ), \"axis\" ) == -1 )";
      segmentonRemoveFromScene_4 = "   {";
      segmentonRemoveFromScene_5 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonRemoveFromScene_6 = "      moveMap.unbindMulti( getWord( %this.Up , 0 ),    getWord( %this.Up , 1 ),    %this, \"onMoveUp\" );";
      segmentonRemoveFromScene_7 = "      moveMap.unbindMulti( getWord( %this.Down , 0 ),  getWord( %this.Down , 1 ),  %this, \"onMoveDown\" );";
      segmentonRemoveFromScene_8 = "   }";
      segmentonRemoveFromScene_9 = "   else";
      segments = "behaviorFields\tonAddToScene\tonRemoveFromScene\tkeepAll";
};
//--- OBJECT WRITE END ---
