//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_05DamageEnergy_Initialization_usesEnergy) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "05 - Damage & Energy";
      description = "This object uses energy.";
      details_atomName = "usesEnergy";
      details_category = "05 - Damage & Energy";
      details_eventAction = "full";
      details_subCategory = "Initialization";
      friendlyName = "Uses Energy";
      segmentbehaviorFields = "4";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Energy_Points\", \"Number of energy points this object has.\", \"float\", 0.0);";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Disabled_At\", \"Disable this object if its energy points drop to (or below) this value. (not same as t2dSceneObject::setEnabled(false) EFM)\", \"float\", -1.0);";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Destroyed_At\", \"Destroy this object if its energy points drop to (or below) this value. (requires takesDamage)\", \"float\", -1.0);";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"Counter\", \"[Optional] Counter name to track energy points.\", \"default\", \"EnergyCounter\");";
      segmentkeepAll = "75";
      segmentkeepAll_0 = "function usesEnergy::initialize(%this) ";
      segmentkeepAll_1 = "{";
      segmentkeepAll_10 = "{";
      segmentkeepAll_11 = "   return ( %this.currentEnergyPoints < %this.Energy_Points );";
      segmentkeepAll_12 = "}";
      segmentkeepAll_13 = "function usesEnergy::applyDrain( %this , %amount )";
      segmentkeepAll_14 = "{ ";
      segmentkeepAll_15 = "   if(!%this.enable) return;";
      segmentkeepAll_16 = "   if(!%this.debugMode) echo(\"usesEnergy::applyDrain( \", %this , \" , \", %amount , \"  ) @ \", getSimTime() );";
      segmentkeepAll_17 = "   if(!%this.debugMode) echo(\"%this.currentEnergyPoints == \", %this.currentEnergyPoints );";
      segmentkeepAll_18 = "   // Apply Drain   ";
      segmentkeepAll_19 = "   %this.currentEnergyPoints -= %amount;";
      segmentkeepAll_2 = "   if(!%this.enable) return;";
      segmentkeepAll_20 = "   %this.currentEnergyPoints = (%this.currentEnergyPoints < 0) ? 0 : %this.currentEnergyPoints;";
      segmentkeepAll_21 = "   %this.currentEnergyPoints = (%this.currentEnergyPoints > %this.Energy_Points) ? %this.Energy_Points : %this.currentEnergyPoints;";
      segmentkeepAll_22 = "   if(isObject(%this.Counter))";
      segmentkeepAll_23 = "   {";
      segmentkeepAll_24 = "      (%this.Counter).setValue(%this.currentEnergyPoints);";
      segmentkeepAll_25 = "   }";
      segmentkeepAll_26 = "   %takesDamageBehavior = %this.owner.getBehavior( \"takesDamage\" );";
      segmentkeepAll_27 = "   // Check to see if this object is destroyed    ";
      segmentkeepAll_28 = "   if( isObject(%takesDamageBehavior) && !%takesDamageBehavior.isDestroyed && ( %this.currentEnergyPoints <= %this.Destroyed_At ) )";
      segmentkeepAll_29 = "   {         ";
      segmentkeepAll_3 = "   %this.currentEnergyPoints = %this.Hit_Points;";
      segmentkeepAll_30 = "      %takesDamageBehavior.destroyObject();";
      segmentkeepAll_31 = "   } ";
      segmentkeepAll_32 = "   else if( !%this.isDisabled && ( %this.currentEnergyPoints <= %this.Disabled_At ) )";
      segmentkeepAll_33 = "   {         ";
      segmentkeepAll_34 = "      %this.broadcastMethod( \"onEnergyDisabled\" );";
      segmentkeepAll_35 = "   } ";
      segmentkeepAll_36 = "   else";
      segmentkeepAll_37 = "   {";
      segmentkeepAll_38 = "      // Broadcast onDrained() callback to other behaviors in this object";
      segmentkeepAll_39 = "      %this.broadcastMethod( onDrained, %amount );";
      segmentkeepAll_4 = "   %this.isDisabled = false;";
      segmentkeepAll_40 = "   }";
      segmentkeepAll_41 = "}";
      segmentkeepAll_42 = "function usesEnergy::applyRecharge( %this , %amount )";
      segmentkeepAll_43 = "{    ";
      segmentkeepAll_44 = "   if(!%this.enable) return;";
      segmentkeepAll_45 = "   if(!%this.debugMode) echo(\"usesEnergy::applyRecharge( \", %this , \" , \", %amount , \"  ) @ \", getSimTime() );";
      segmentkeepAll_46 = "   // Apply Drain   ";
      segmentkeepAll_47 = "   %this.currentEnergyPoints += %amount;";
      segmentkeepAll_48 = "   %this.currentEnergyPoints = (%this.currentEnergyPoints < 0) ? 0 : %this.currentEnergyPoints;";
      segmentkeepAll_49 = "   %this.currentEnergyPoints = (%this.currentEnergyPoints > %this.Energy_Points) ? %this.Energy_Points : %this.currentEnergyPoints;";
      segmentkeepAll_5 = "}";
      segmentkeepAll_50 = "   if(isObject(%this.Counter))";
      segmentkeepAll_51 = "   {";
      segmentkeepAll_52 = "      (%this.Counter).setValue(%this.currentEnergyPoints);";
      segmentkeepAll_53 = "   }";
      segmentkeepAll_54 = "   ";
      segmentkeepAll_55 = "   %takesDamageBehavior = %this.owner.getBehavior( \"takesDamage\" );";
      segmentkeepAll_56 = "   // Check to see if this object is destroyed    ";
      segmentkeepAll_57 = "   if( isObject(%takesDamageBehavior) && !%takesDamageBehavior.isDestroyed && ( %this.currentEnergyPoints <= %this.Destroyed_At ) )";
      segmentkeepAll_58 = "   {         ";
      segmentkeepAll_59 = "      %takesDamageBehavior.destroyObject();";
      segmentkeepAll_6 = "//";
      segmentkeepAll_60 = "   } ";
      segmentkeepAll_61 = "   else if( !%this.isDisabled && ( %this.currentEnergyPoints <= %this.Disabled_At ) )";
      segmentkeepAll_62 = "   {         ";
      segmentkeepAll_63 = "      %this.broadcastMethod( \"onEnergyEnabled\" );";
      segmentkeepAll_64 = "   } ";
      segmentkeepAll_65 = "   else if( %this.isDisabled && ( %this.currentEnergyPoints > %this.Disabled_At ) )";
      segmentkeepAll_66 = "   {         ";
      segmentkeepAll_67 = "      %this.broadcastMethod( onEnabled );";
      segmentkeepAll_68 = "   } ";
      segmentkeepAll_69 = "   else";
      segmentkeepAll_7 = "// Methods";
      segmentkeepAll_70 = "   {";
      segmentkeepAll_71 = "      // Broadcast onDrained() callback to other behaviors in this object";
      segmentkeepAll_72 = "      %this.broadcastMethod( onRecharged, %amount );";
      segmentkeepAll_73 = "   }";
      segmentkeepAll_74 = "}";
      segmentkeepAll_8 = "//";
      segmentkeepAll_9 = "function usesEnergy::isDrained( %this )";
      segmentonAddToScene = "1";
      segmentonAddToScene_0 = "   %this.initialize();";
      segmentonLevelLoaded = "4";
      segmentonLevelLoaded_0 = "   if(isObject(%this.Counter))";
      segmentonLevelLoaded_1 = "   {";
      segmentonLevelLoaded_2 = "      (%this.Counter).setValue(%this.currentEnergyPoints);";
      segmentonLevelLoaded_3 = "   }";
      segments = "behaviorFields\tonLevelLoaded\tonAddToScene\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_05DamageEnergy_Initialization_takesDamage) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "05 - Damage & Energy";
      description = "This object takes damage.";
      details_atomName = "takesDamage";
      details_category = "05 - Damage & Energy";
      details_eventAction = "full";
      details_subCategory = "Initialization";
      friendlyName = "Takes Damage";
      segmentbehaviorFields = "3";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Hit_Points\", \"Number of hit points this object has.\", \"float\", 0.0);";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Destroyed_At\", \"Destroy this object if its hit points drop to (or below) this value.\", \"float\", -1.0);";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Counter\", \"[Optional] Counter name to track hit points.\", \"default\", \"HPCounter\");";
      segmentkeepAll = "74";
      segmentkeepAll_0 = "function takesDamage::initialize(%this) ";
      segmentkeepAll_1 = "{";
      segmentkeepAll_10 = "{";
      segmentkeepAll_11 = "   return ( %this.currentHitPoints < %this.Hit_Points );";
      segmentkeepAll_12 = "}";
      segmentkeepAll_13 = "function takesDamage::applyDamage( %this , %amount )";
      segmentkeepAll_14 = "{ ";
      segmentkeepAll_15 = "   if(!%this.enable) return;";
      segmentkeepAll_16 = "   if(!%this.debugMode) echo(\"takesDamage::applyDamage( \", %this , \" , \", %amount , \"  ) @ \", getSimTime() );";
      segmentkeepAll_17 = "   if(!%this.debugMode) echo(\"%this.currentHitPoints == \", %this.currentHitPoints );";
      segmentkeepAll_18 = "   // Apply damage   ";
      segmentkeepAll_19 = "   %this.currentHitPoints -= %amount;";
      segmentkeepAll_2 = "   if(!%this.enable) return;";
      segmentkeepAll_20 = "   %this.currentHitPoints = (%this.currentHitPoints < 0) ? 0 : %this.currentHitPoints;";
      segmentkeepAll_21 = "   %this.currentHitPoints = (%this.currentHitPoints > %this.Hit_Points) ? %this.Hit_Points : %this.currentHitPoints;";
      segmentkeepAll_22 = "   if(isObject(%this.Counter))";
      segmentkeepAll_23 = "   {";
      segmentkeepAll_24 = "      (%this.Counter).setValue(%this.currentHitPoints);";
      segmentkeepAll_25 = "   }";
      segmentkeepAll_26 = "   ";
      segmentkeepAll_27 = "   // Check to see if this object is destroyed    ";
      segmentkeepAll_28 = "   if( !%this.isDestroyed && ( %this.currentHitPoints <= %this.Destroyed_At ) )";
      segmentkeepAll_29 = "   { ";
      segmentkeepAll_3 = "   %this.currentHitPoints = %this.Hit_Points;";
      segmentkeepAll_30 = "      if(!%this.debugMode) echo(\"Destroying object == \", %this.owner.getname() );";
      segmentkeepAll_31 = "        ";
      segmentkeepAll_32 = "      %this.destroyObject();";
      segmentkeepAll_33 = "   } ";
      segmentkeepAll_34 = "   else";
      segmentkeepAll_35 = "   {";
      segmentkeepAll_36 = "      // Broadcast onDamaged() callback to other behaviors in this object";
      segmentkeepAll_37 = "      %this.broadcastMethod( \"onDamaged\", %amount );";
      segmentkeepAll_38 = "   }";
      segmentkeepAll_39 = "}";
      segmentkeepAll_4 = "   %this.isDestroyed = false;";
      segmentkeepAll_40 = "function takesDamage::applyRepair( %this , %amount )";
      segmentkeepAll_41 = "{ ";
      segmentkeepAll_42 = "   if(!%this.enable) return;";
      segmentkeepAll_43 = "   if(!%this.debugMode) echo(\"takesDamage::applyRepair( \", %this , \" , \", %amount , \"  ) @ \", getSimTime() );";
      segmentkeepAll_44 = "   // Apply damage   ";
      segmentkeepAll_45 = "   %this.currentHitPoints += %amount;";
      segmentkeepAll_46 = "   %this.currentHitPoints = (%this.currentHitPoints < 0) ? 0 : %this.currentHitPoints;";
      segmentkeepAll_47 = "   %this.currentHitPoints = (%this.currentHitPoints > %this.Hit_Points) ? %this.Hit_Points : %this.currentHitPoints;";
      segmentkeepAll_48 = "   if(isObject(%this.Counter))";
      segmentkeepAll_49 = "   {";
      segmentkeepAll_5 = "}";
      segmentkeepAll_50 = "      (%this.Counter).setValue(%this.currentHitPoints);";
      segmentkeepAll_51 = "   }";
      segmentkeepAll_52 = "   ";
      segmentkeepAll_53 = "   // Check to see if this object is destroyed    ";
      segmentkeepAll_54 = "   if( !%this.isDestroyed && ( %this.currentHitPoints <= %this.Destroyed_At ) )";
      segmentkeepAll_55 = "   {         ";
      segmentkeepAll_56 = "      %this.destroyObject();";
      segmentkeepAll_57 = "   } ";
      segmentkeepAll_58 = "   else";
      segmentkeepAll_59 = "   {";
      segmentkeepAll_6 = "//";
      segmentkeepAll_60 = "      // Broadcast onDamaged() callback to other behaviors in this object";
      segmentkeepAll_61 = "      %this.broadcastMethod( \"onRepaired\", %amount );";
      segmentkeepAll_62 = "   }";
      segmentkeepAll_63 = "}";
      segmentkeepAll_64 = "function takesDamage::destroyObject( %this )";
      segmentkeepAll_65 = "{";
      segmentkeepAll_66 = "   if(!%this.enable) return;";
      segmentkeepAll_67 = "   //echo(\"takesDamage::destroyObject( \", %this , \"  ) @ \", getSimTime() );";
      segmentkeepAll_68 = "   %this.isDestroyed = true;";
      segmentkeepAll_69 = "   // Broadcast onDestroyed() callback to other behaviors in this object";
      segmentkeepAll_7 = "// Methods";
      segmentkeepAll_70 = "   %this.broadcastMethod( \"onDestroyed\" );";
      segmentkeepAll_71 = "   //%this.owner.collisionActiveReceive = false;";
      segmentkeepAll_72 = "   %this.owner.setEnabled(false);   ";
      segmentkeepAll_73 = "}";
      segmentkeepAll_8 = "//";
      segmentkeepAll_9 = "function takesDamage::isDamaged( %this )";
      segmentonAddToScene = "1";
      segmentonAddToScene_0 = "   %this.initialize();";
      segmentonLevelLoaded = "4";
      segmentonLevelLoaded_0 = "   if(isObject(%this.Counter))";
      segmentonLevelLoaded_1 = "   {";
      segmentonLevelLoaded_2 = "      (%this.Counter).setValue(%this.currentHitPoints);";
      segmentonLevelLoaded_3 = "   }";
      segments = "behaviorFields\tonLevelLoaded\tonAddToScene\tkeepAll";
};
//--- OBJECT WRITE END ---
