//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_05DamageEnergy_Area_onDestroyed_DoAreaDrain) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "05 - Damage & Energy";
      description = "This object drains other objects in the area when it is destroyed.";
      details_atomName = "onDestroyed_DoAreaDrain";
      details_category = "05 - Damage & Energy";
      details_eventAction = "full";
      details_subCategory = "Area";
      friendlyName = "onDestroyed() -> Do Area Drain (manual)";
      segmentbehaviorFields = "5";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Drain\", \"Do this much drain to objects in a specified radius.\", float, 0.0);";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Drain_Groups\", \"Apply drain to objects in these graph groups.\", \"bitmask\", \"0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31\");   ";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Drain_Radius\", \"Radius to drain in.\", float, 0.0);";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"Drain_Falloff\", \"Drain falls off as specified.\", ENUM, \"ZERO\", \"ZERO\\tLINEAR\\tLOG\");";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"Drain_Delay\", \"Wait this many milliseconds before applying drain to objects.\", \"integer\", 0);";
      segmentkeepAll = "73";
      segmentkeepAll_0 = "function onDestroyed_DoAreaDrain::onDestroyed(%this) ";
      segmentkeepAll_1 = "{";
      segmentkeepAll_10 = "   %pickBits     = bits( %pickGroups );";
      segmentkeepAll_11 = "   ";
      segmentkeepAll_12 = "   if( (%this.Drain > 0) && (%this.Drain_Radius > 0))";
      segmentkeepAll_13 = "   {";
      segmentkeepAll_14 = "      %tmpTokens = %sceneGraph.pickRadius( %pickPosition, %pickRadius, %pickBits);";
      segmentkeepAll_15 = "      ";
      segmentkeepAll_16 = "      while( \"\" !$= %tmpTokens ) ";
      segmentkeepAll_17 = "      {";
      segmentkeepAll_18 = "         %tmpTokens = nextToken( %tmpTokens , \"theToken\" , \" \" );";
      segmentkeepAll_19 = "         ";
      segmentkeepAll_2 = "   if(!%this.enable) return;";
      segmentkeepAll_20 = "         %theID = %theToken.getID();";
      segmentkeepAll_21 = "         ";
      segmentkeepAll_22 = "         %isOwner = (%owner == %theID);";
      segmentkeepAll_23 = "         ";
      segmentkeepAll_24 = "         %drainBehavior = %theID.getBehavior( \"usesEnergy\" );";
      segmentkeepAll_25 = "      ";
      segmentkeepAll_26 = "         if( ( isObject(%drainBehavior) ) && !%isOwner )";
      segmentkeepAll_27 = "         {";
      segmentkeepAll_28 = "            %this.applyAreaDrain( %drainBehavior, %theID,";
      segmentkeepAll_29 = "                                   %this.Drain_Radius, %this.Drain, ";
      segmentkeepAll_3 = "   if(!%this.debugMode) echo(\"onDestroyed_DoAreaDrain::onDestroyed(\" SPC %this SPC \")\");";
      segmentkeepAll_30 = "                                   %this.Drain_Falloff, %this.Drain_Delay );";
      segmentkeepAll_31 = "         }";
      segmentkeepAll_32 = "      }";
      segmentkeepAll_33 = "     ";
      segmentkeepAll_34 = "   }";
      segmentkeepAll_35 = "}";
      segmentkeepAll_36 = "function onDestroyed_DoAreaDrain::applyAreaDrain( %this, %drainBehavior, ";
      segmentkeepAll_37 = "                                                    %targetID,";
      segmentkeepAll_38 = "                                                    %radius, %amount, %falloff, ";
      segmentkeepAll_39 = "                                                    %delay )";
      segmentkeepAll_4 = "   ";
      segmentkeepAll_40 = "{ ";
      segmentkeepAll_41 = "   if(!%this.enable) return;";
      segmentkeepAll_42 = "   if(!%this.debugMode) echo(\"onDestroyed_DoAreaDrain::applyAreaDrain( \", %this, \", \", %drainBehavior, \"  ) @ \", getSimTime() );";
      segmentkeepAll_43 = "   ";
      segmentkeepAll_44 = "   %targetPos = %targetID.getPosition();";
      segmentkeepAll_45 = "   %srcPos = %this.owner.getPosition();";
      segmentkeepAll_46 = "   ";
      segmentkeepAll_47 = "   // 1";
      segmentkeepAll_48 = "   %distance = t2dVectorDistance( %targetPos , %srcPos );";
      segmentkeepAll_49 = "   ";
      segmentkeepAll_5 = "   %owner        = %this.owner.getID();";
      segmentkeepAll_50 = "   // 2";
      segmentkeepAll_51 = "   switch$( %falloff )";
      segmentkeepAll_52 = "   {";
      segmentkeepAll_53 = "   case \"ZERO\": // Drain fall-off by distance == 0";
      segmentkeepAll_54 = "      %amount = %amount;";
      segmentkeepAll_55 = "      ";
      segmentkeepAll_56 = "   case \"LINEAR\": // Drain fall-off by distance == ( radius - distance ) / radius";
      segmentkeepAll_57 = "      %amount = %amount * ( ( %radius - %distance ) / %radius );";
      segmentkeepAll_58 = "         ";
      segmentkeepAll_59 = "   case \"LOG\": // Drain fall-off by distance == 01 - log( distance ) / log( radius )";
      segmentkeepAll_6 = "   %pickPosition = %owner.getPosition();";
      segmentkeepAll_60 = "      if( %distance < 1 )";
      segmentkeepAll_61 = "      {";
      segmentkeepAll_62 = "         %amount = %amount;";
      segmentkeepAll_63 = "      }";
      segmentkeepAll_64 = "      else";
      segmentkeepAll_65 = "      {";
      segmentkeepAll_66 = "         %amount = %amount * ( 01 - mLog( %distance ) / mLog( %radius ) );            ";
      segmentkeepAll_67 = "      }";
      segmentkeepAll_68 = "   }";
      segmentkeepAll_69 = "   ";
      segmentkeepAll_7 = "   %pickRadius   = %this.Drain_Radius;";
      segmentkeepAll_70 = "   // 3";
      segmentkeepAll_71 = "   %drainBehavior.schedule(%delay, applyDrain, %amount );  ";
      segmentkeepAll_72 = "}";
      segmentkeepAll_8 = "   %sceneGraph   = %owner.getSceneGraph();";
      segmentkeepAll_9 = "   %pickGroups   = %this.Drain_Groups;";
      segments = "behaviorFields\tkeepAll";
};
//--- OBJECT WRITE END ---
//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_05DamageEnergy_Area_onDestroyed_DoAreaDamage) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "05 - Damage & Energy";
      description = "This object damages other objects in the area when it is destroyed.";
      details_atomName = "onDestroyed_DoAreaDamage";
      details_category = "05 - Damage & Energy";
      details_eventAction = "full";
      details_subCategory = "Area";
      friendlyName = "onDestroyed() -> Do Area Damage (manual)";
      segmentbehaviorFields = "5";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"Damage\", \"Do this much damage to objects in a specified radius.\", float, 0.0);";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"Damage_Groups\", \"Apply damage to objects in these graph groups.\", \"bitmask\", \"0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31\");   ";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"Damage_Radius\", \"Radius to damage in.\", float, 0.0);";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"Damage_Falloff\", \"Damage falls off as specified.\", ENUM, \"ZERO\", \"ZERO\\tLINEAR\\tLOG\");";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField( \"Damage_Delay\", \"Wait this many milliseconds before applying damage to objects.\", \"integer\", 0);";
      segmentkeepAll = "73";
      segmentkeepAll_0 = "function onDestroyed_DoAreaDamage::onDestroyed(%this) ";
      segmentkeepAll_1 = "{";
      segmentkeepAll_10 = "   %pickBits     = bits( %pickGroups );";
      segmentkeepAll_11 = "   ";
      segmentkeepAll_12 = "   if( (%this.Damage > 0) && (%this.Damage_Radius > 0))";
      segmentkeepAll_13 = "   {";
      segmentkeepAll_14 = "      %tmpTokens = %sceneGraph.pickRadius( %pickPosition, %pickRadius, %pickBits);";
      segmentkeepAll_15 = "      ";
      segmentkeepAll_16 = "      while( \"\" !$= %tmpTokens ) ";
      segmentkeepAll_17 = "      {";
      segmentkeepAll_18 = "         %tmpTokens = nextToken( %tmpTokens , \"theToken\" , \" \" );";
      segmentkeepAll_19 = "         ";
      segmentkeepAll_2 = "   if(!%this.enable) return;";
      segmentkeepAll_20 = "         %theID = %theToken.getID();";
      segmentkeepAll_21 = "         ";
      segmentkeepAll_22 = "         %isOwner = (%owner == %theID);";
      segmentkeepAll_23 = "         ";
      segmentkeepAll_24 = "         %damageBehavior = %theID.getBehavior( \"takesDamage\" );";
      segmentkeepAll_25 = "      ";
      segmentkeepAll_26 = "         if( ( isObject(%damageBehavior) ) && !%isOwner )";
      segmentkeepAll_27 = "         {";
      segmentkeepAll_28 = "            %this.applyAreaDamage( %damageBehavior, %theID,";
      segmentkeepAll_29 = "                                   %this.Damage_Radius, %this.Damage, ";
      segmentkeepAll_3 = "   if(!%this.debugMode) echo(\"onDestroyed_DoAreaDamage::onDestroyed(\" SPC %this SPC \")\");";
      segmentkeepAll_30 = "                                   %this.Damage_Falloff, %this.Damage_Delay );";
      segmentkeepAll_31 = "         }";
      segmentkeepAll_32 = "      }";
      segmentkeepAll_33 = "     ";
      segmentkeepAll_34 = "   }";
      segmentkeepAll_35 = "}";
      segmentkeepAll_36 = "function onDestroyed_DoAreaDamage::applyAreaDamage( %this, %damageBehavior, ";
      segmentkeepAll_37 = "                                                    %targetID,";
      segmentkeepAll_38 = "                                                    %radius, %amount, %falloff, ";
      segmentkeepAll_39 = "                                                    %delay )";
      segmentkeepAll_4 = "   ";
      segmentkeepAll_40 = "{ ";
      segmentkeepAll_41 = "   if(!%this.enable) return;";
      segmentkeepAll_42 = "   if(!%this.debugMode) echo(\"onDestroyed_DoAreaDamage::applyAreaDamage( \", %this, \", \", %damageBehavior, \"  ) @ \", getSimTime() );";
      segmentkeepAll_43 = "   ";
      segmentkeepAll_44 = "   %targetPos = %targetID.getPosition();";
      segmentkeepAll_45 = "   %srcPos = %this.owner.getPosition();";
      segmentkeepAll_46 = "   ";
      segmentkeepAll_47 = "   // 1";
      segmentkeepAll_48 = "   %distance = t2dVectorDistance( %targetPos , %srcPos );";
      segmentkeepAll_49 = "   ";
      segmentkeepAll_5 = "   %owner        = %this.owner.getID();";
      segmentkeepAll_50 = "   // 2";
      segmentkeepAll_51 = "   switch$( %falloff )";
      segmentkeepAll_52 = "   {";
      segmentkeepAll_53 = "   case \"ZERO\": // Damage fall-off by distance == 0";
      segmentkeepAll_54 = "      %amount = %amount;";
      segmentkeepAll_55 = "      ";
      segmentkeepAll_56 = "   case \"LINEAR\": // Damage fall-off by distance == ( radius - distance ) / radius";
      segmentkeepAll_57 = "      %amount = %amount * ( ( %radius - %distance ) / %radius );";
      segmentkeepAll_58 = "         ";
      segmentkeepAll_59 = "   case \"LOG\": // Damage fall-off by distance == 01 - log( distance ) / log( radius )";
      segmentkeepAll_6 = "   %pickPosition = %owner.getPosition();";
      segmentkeepAll_60 = "      if( %distance < 1 )";
      segmentkeepAll_61 = "      {";
      segmentkeepAll_62 = "         %amount = %amount;";
      segmentkeepAll_63 = "      }";
      segmentkeepAll_64 = "      else";
      segmentkeepAll_65 = "      {";
      segmentkeepAll_66 = "         %amount = %amount * ( 01 - mLog( %distance ) / mLog( %radius ) );            ";
      segmentkeepAll_67 = "      }";
      segmentkeepAll_68 = "   }";
      segmentkeepAll_69 = "   ";
      segmentkeepAll_7 = "   %pickRadius   = %this.Damage_Radius;";
      segmentkeepAll_70 = "   // 3";
      segmentkeepAll_71 = "   %damageBehavior.schedule(%delay, applyDamage, %amount );  ";
      segmentkeepAll_72 = "}";
      segmentkeepAll_8 = "   %sceneGraph   = %owner.getSceneGraph();";
      segmentkeepAll_9 = "   %pickGroups   = %this.Damage_Groups;";
      segments = "behaviorFields\tkeepAll";
};
//--- OBJECT WRITE END ---
