//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_12MountedObjects_Tires_aTire) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "12 - Mounted Objects";
      description = "This object should behave like a tire and rotate left-right (in response to key inputs).  It can also have a base-rotation not affected by key inputs.";
      details_atomName = "aTire";
      details_category = "12 - Mounted Objects";
      details_eventAction = "full";
      details_subCategory = "Tires";
      friendlyName = "A Tire (multi)";
      segmentbehaviorFields = "4";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField( \"baseRotation\", \"Default rotation rate when no keys are pressed. (Degrees-per-second)\", float, 90 );   ";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField( \"keyRotation\", \"Rotation added (or subtracted as result of pressing key. (Degrees-per-second)\", float, 90 );   ";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField( \"leftKey\",  \"Rotate left\",  keybind, \"Keyboard A\" );";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField( \"rightKey\", \"Rotate right\", keybind, \"Keyboard D\" );";
      segmentkeepAll = "51";
      segmentkeepAll_0 = "function aTire::onRotateleftKey( %this , %val )";
      segmentkeepAll_1 = "{   ";
      segmentkeepAll_10 = "      %val = -%val; // Flip to get proper direction";
      segmentkeepAll_11 = "   }";
      segmentkeepAll_12 = "   %this.inputX  = %val;";
      segmentkeepAll_13 = "   %this.doRotate();";
      segmentkeepAll_14 = "}";
      segmentkeepAll_15 = "function aTire::onRotaterightKey( %this , %val )";
      segmentkeepAll_16 = "{   ";
      segmentkeepAll_17 = "   //error(\"aTire::onRotaterightKey( \", %val , \" ) \" );";
      segmentkeepAll_18 = "   %this.rightKey = %val;";
      segmentkeepAll_19 = "   if(!%val && %this.leftKey) %val = -1; ";
      segmentkeepAll_2 = "   //error(\"aTire::onRotateleftKey( \", %val , \" ) \" );";
      segmentkeepAll_20 = "   %this.inputX  = %val;";
      segmentkeepAll_21 = "   ";
      segmentkeepAll_22 = "   %this.doRotate();";
      segmentkeepAll_23 = "}";
      segmentkeepAll_24 = "function aTire::onRotateJoystickleftKeyClockwise( %this , %val )";
      segmentkeepAll_25 = "{   ";
      segmentkeepAll_26 = "   //error(\"aTire::onRotateJoystickleftKeyClockwise( \", %val , \" ) \" );";
      segmentkeepAll_27 = "   ";
      segmentkeepAll_28 = "   // rightKey";
      segmentkeepAll_29 = "   if( %val < 0 )";
      segmentkeepAll_3 = "   %this.leftKey = %val;";
      segmentkeepAll_30 = "   {";
      segmentkeepAll_31 = "      %this.inputX = %val;";
      segmentkeepAll_32 = "      %this.inputX = mFloor(%this.inputX);";
      segmentkeepAll_33 = "   }";
      segmentkeepAll_34 = "   // leftKey";
      segmentkeepAll_35 = "   else if (%val > 0)";
      segmentkeepAll_36 = "   {";
      segmentkeepAll_37 = "      %this.inputX = %val;";
      segmentkeepAll_38 = "      %this.inputX = mCeil(%this.inputX);";
      segmentkeepAll_39 = "   }";
      segmentkeepAll_4 = "   if(!%val && %this.rightKey) ";
      segmentkeepAll_40 = "   // Off";
      segmentkeepAll_41 = "   else";
      segmentkeepAll_42 = "   {";
      segmentkeepAll_43 = "      %this.inputX = 0;";
      segmentkeepAll_44 = "   }";
      segmentkeepAll_45 = "   %this.doRotate();";
      segmentkeepAll_46 = "}";
      segmentkeepAll_47 = "function aTire::doRotate( %this )";
      segmentkeepAll_48 = "{   ";
      segmentkeepAll_49 = "   %this.owner.setAngularVelocity( %this.inputX * %this.keyRotation  + %this.baseRotation );";
      segmentkeepAll_5 = "   {";
      segmentkeepAll_50 = "}";
      segmentkeepAll_6 = "      %val = 1;";
      segmentkeepAll_7 = "   }";
      segmentkeepAll_8 = "   else";
      segmentkeepAll_9 = "   {";
      segmentonAddToScene = "22";
      segmentonAddToScene_0 = "   %this.owner.MountTrackRotation = \"0\";";
      segmentonAddToScene_1 = "   ";
      segmentonAddToScene_10 = "      moveMap.bindMulti( getWord( %this.rightKey , 0 ), getWord( %this.rightKey , 1 ), %this, \"onRotaterightKey\" );";
      segmentonAddToScene_11 = "   }";
      segmentonAddToScene_12 = "   else";
      segmentonAddToScene_13 = "   {";
      segmentonAddToScene_14 = "      // USING JOYSTICK AXIS";
      segmentonAddToScene_15 = "      moveMap.bindMulti( getWord( %this.leftKey , 0 ), getWord( %this.leftKey , 1 ), %this, \"onRotateJoystickleftKeyClockwise\" );";
      segmentonAddToScene_16 = "   }";
      segmentonAddToScene_17 = "  ";
      segmentonAddToScene_18 = "   %this.inputX = 0;";
      segmentonAddToScene_19 = "   %this.inputY = 0;";
      segmentonAddToScene_2 = "   %this.owner.setAngularVelocity( %this.baseRotation );";
      segmentonAddToScene_20 = "   %this.leftKey = 0;";
      segmentonAddToScene_21 = "   %this.rightKey = 0;";
      segmentonAddToScene_3 = "   ";
      segmentonAddToScene_4 = "   // Note: Do not use a joystick for only one part of a Rotation pair. ";
      segmentonAddToScene_5 = "   // Ex: If you use joystick yaxis for up, use it for down too.";
      segmentonAddToScene_6 = "   if( strstr( getWord( %this.leftKey , 1 ), \"axis\" ) == -1 )";
      segmentonAddToScene_7 = "   {";
      segmentonAddToScene_8 = "      // USING JOYSTICK BUTTONS OR KEYBOARD KEYS";
      segmentonAddToScene_9 = "      moveMap.bindMulti( getWord( %this.leftKey , 0 ),  getWord( %this.leftKey , 1 ),  %this, \"onRotateleftKey\" );";
      segments = "behaviorFields\tonAddToScene\tkeepAll";
};
//--- OBJECT WRITE END ---
