//--- OBJECT WRITE BEGIN ---
new ScriptObject(full_31EasyGUIs_CounterMeters_easyMeterUpdate) {
   canSaveDynamicFields = "1";
   class = "behaviorAtom";
      behaviorType = "31 - Easy GUIs";
      description = "Update a named (easy) meter on a regular basis, using the owner\'s damage, energy, etc as a data source.";
      details_atomName = "easyMeterUpdate";
      details_category = "31 - Easy GUIs";
      details_eventAction = "full";
      details_subCategory = "Counter & Meters";
      friendlyName = "Easy Meter Updater";
      segmentbehaviorFields = "5";
      segmentbehaviorFields_0 = "   %behavior.addBehaviorField(enable, \"Enable this behavior.\", bool, true);";
      segmentbehaviorFields_1 = "   %behavior.addBehaviorField(debugMode, \"Enable debugging (output) for this behavior.\", bool, false);";
      segmentbehaviorFields_2 = "   %behavior.addBehaviorField(meterName, \"Meter to update.\", \"default\", \"\");";
      segmentbehaviorFields_3 = "   %behavior.addBehaviorField(dataType, \"Type of data to post to meter.\", \"enum\", \"damage\", \"damage\"TAB\"energy\"); //EFM maybe more later";
      segmentbehaviorFields_4 = "   %behavior.addBehaviorField(updateFreq, \"Updates per second.\", \"enum\", \"1\", \"1\"TAB\"2\"TAB\"3\"TAB\"4\"TAB\"5\"TAB\"6\"TAB\"7\"TAB\"8\"TAB\"9\"TAB\"10\");";
      segmentkeepAll = "27";
      segmentkeepAll_0 = "function easyMeterUpdate::updateMeter(%this, %period)";
      segmentkeepAll_1 = "{";
      segmentkeepAll_10 = "         %curPercent = %this.owner.getCurrentDamagePercent();";
      segmentkeepAll_11 = "         %curVal = 1.0 - %this.owner.getCurrentDamagePercent()/100;";
      segmentkeepAll_12 = "      case \"energy\":";
      segmentkeepAll_13 = "         %curPercent = %this.owner.getCurrentEnergyPercent();";
      segmentkeepAll_14 = "         %curVal = 1.0 - %this.owner.getCurrentEnergyPercent()/100;         ";
      segmentkeepAll_15 = "      }";
      segmentkeepAll_16 = "      ";
      segmentkeepAll_17 = "      if(%this.debugMode) echo(%this.getName() @ \"::updateMeter() - Meter \", %this.meterName, \" %curPercent == \", %curPercent);";
      segmentkeepAll_18 = "      if(%this.debugMode) echo(%this.getName() @ \"::updateMeter() - Setting meter \", %this.meterName, \" to \", %curVal);";
      segmentkeepAll_19 = "      (%this.meterName).setValue( %curVal );";
      segmentkeepAll_2 = "   if(!%this.enable) return;";
      segmentkeepAll_20 = "    }";
      segmentkeepAll_21 = "    else";
      segmentkeepAll_22 = "    {";
      segmentkeepAll_23 = "       if(%this.debugMode) echo(%this.getName() @ \"::updateMeter() - Unknown meter name\");";
      segmentkeepAll_24 = "    }";
      segmentkeepAll_25 = "    %this.schedule( %period, updateMeter, %period );";
      segmentkeepAll_26 = "}";
      segmentkeepAll_3 = "   if(%this.debugMode) echo(%this.getName() @ \"::updateMeter()\");";
      segmentkeepAll_4 = "   if(isObject(%this.meterName))";
      segmentkeepAll_5 = "   {";
      segmentkeepAll_6 = "      %curVal = 0;";
      segmentkeepAll_7 = "      switch$(%this.dataType)";
      segmentkeepAll_8 = "      {";
      segmentkeepAll_9 = "      case \"damage\":";
      segmentonLevelLoaded = "1";
      segmentonLevelLoaded_0 = "   %this.schedule( 1000/%this.updateFreq, updateMeter, 1000/%this.updateFreq );";
      segments = "behaviorFields\tonLevelLoaded\tkeepAll";
};
//--- OBJECT WRITE END ---
