// This behavior generated by the Roaming Gamer Behavior Generator
//ACTION ATOM DETAILS
//   Category: 40 - Game Logic
//Subcategory: SimSets
//Action Name: onAddToSceneAddtoSimSet

//registerAtom( action | event | full, "Category", "SubCategory", "BehaviorName" );

if (!isObject(onAddToSceneAddtoSimSet))
{
   %behavior = new BehaviorTemplate(onAddToSceneAddtoSimSet) 
   { 

      friendlyName = "onAddToScene() -> Add to SimSet";
      behaviorType = "40 - Game Logic";
      description = "Automatically add this object to the specified SimSet upon adding it to the scene.";

   };
   %behavior.addBehaviorField(enable, "Enable this behavior.", bool, true);
   %behavior.addBehaviorField(debugMode, "Enable debugging (output) for this behavior.", bool, false);
   %behavior.addBehaviorField(setName, "Name of SimSet to add this objec to. (Creates set if not yet present.)", "default", "theSet");
}

function onAddToSceneAddtoSimSet::onAddToScene(%this, %scenegraph)
{
   if(!%this.enable) return;
   if(%this.debugMode) echo(%this.getName() @ "::onAddToScene()");

   //Action Atom Code:onAddToScene() -> Add to SimSet
   if(!isObject( %this.setName )) new SimSet( %this.setName );
   ( %this.setName ).add( %this.owner );

}//onAddToScene

