// This behavior generated by the Roaming Gamer Behavior Generator
//ACTION ATOM DETAILS
//   Category: 00 - Rapid Prototyping
//Subcategory: Level Management
//Action Name: onKeyUpEndGame

//registerAtom( action | event | full, "Category", "SubCategory", "BehaviorName" );

if (!isObject(onKeyUpEndGame))
{
   %behavior = new BehaviorTemplate(onKeyUpEndGame) 
   { 

      friendlyName = "onKeyUp() -> endGame()";
      behaviorType = "00 - Rapid Prototyping / Game Management";
      description = "When a key is released call endGame().";

   };
   %behavior.addBehaviorField(enable, "Enable this behavior.", bool, true);
   %behavior.addBehaviorField(debugMode, "Enable debugging (output) for this behavior.", bool, false);
   %behavior.addBehaviorField( "actionKey",   "Key that is pressed to cause an action.", keybind, "Keyboard escape" );
}

function onKeyUpEndGame::onAddToScene(%this, %scenegraph)
{
   if(!%this.enable) return;
   if(%this.debugMode) echo(%this.getName() @ "::onAddToScene()");

   //Action Atom Code:onKeyUp() -> reloadCurrentLevel
   //Event Atom Code:onKeyUp() ->
   moveMap.bindCmd( getWord(%this.actionKey, 0), 
                    getWord(%this.actionKey, 1), 
                    "",
                    "endGame();" );

}//onAddToScene

